### ISSUE TITLE
If we wanted to replace the below where would we look in the code base to plug in alternatives ?

### ISSUE THREAD

**Issue by fredhampton** [DemocracyEarth/sovereign#101]
If we wanted to replace the below where would we look in the code base to plug in alternatives ?

 Decentralized identity key management 🔗 with Blockstack.
 Institutional incorporation via smart contracts 🔗 with Open Zeppelin.
 Bitcoin integration for budgeting 🔗 with Bcoin.
 Distributed resource storage 🔗 with IPFS.

**Comment by santisiri** [comment]
Hi @fredhampton, great question.

For the first three (blockchain related) I'd start with `imports/api/transactions/transaction.js` as I referred in #102.

In the case of IPFS, you can start with something relatively simple as replacing it by the current AWS  implementation in the app that is strictly being used to upload avatar pictures. `imports/ui/modules/Files.js` would be a good place to get started for that. I would leave the AWS implementation and add an IPFS one (and have an app setting to switch that).
