### ISSUE TITLE
 We have a private block chain. How do we plug our block chain into Sovereign ?

### ISSUE THREAD

**Issue by fredhampton** [DemocracyEarth/sovereign#102]
We have a private block chain. How do we plug our block chain into Sovereign ?

**Comment by santisiri** [comment]
Hi @fredhampton, sorry for the late reply. 

I would start with `imports/api/transactions/transaction.js`

It has this three simple methods that are called throughout the whole app:

```js
export const processTransaction = _processTransaction;
export const generateWalletAddress = _generateWalletAddress;
export const transact = _createTransaction;
```

- `transact` to make a transaction (will store in db 'Transaction' collection)
- `generateWalletAddress` to create an address if an entity or user needs it
- `processTransaction` to update the status of all the wallets impacted by this.

As mentioned in the `README`, app is still blockchain agnostic so suggestions are welcomed. 

Glad to help in any way.
