### ISSUE TITLE
Cannot install on Windows - bcrypt issue

### ISSUE THREAD

**Issue by tadhgpearson** [DemocracyEarth/sovereign#105]
When following the install instructions in the README on Windows 7, install fails at step 3 `npm install` with the following error:

`npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     D:\git\sovereign\npm-debug.log
npm ERR! not ok code 0`

Investigating the debug log yields the following further info

'18795 error bcrypt@0.8.7 install: `node-gyp rebuild`
18795 error Exit status 1
18796 error Failed at the bcrypt@0.8.7 install script.
18796 error This is most likely a problem with the bcrypt package,
18796 error not with npm itself.
18796 error Tell the author that this fails on your system:
18796 error     node-gyp rebuild
18796 error You can get their info via:
18796 error     npm owner ls bcrypt
18796 error There is likely additional logging output above.
18797 error System Windows_NT 6.1.7601
18798 error command "C:\\Program Files\\nodejs\\node.exe" "C:\\lib\\npm\\tools\\node_modules\\npm\\bin\\npm-cli.js" "install"
18799 error cwd D:\git\sovereign
18800 error node -v v7.1.0
18801 error npm -v 1.4.9
18802 error code ELIFECYCLE
18803 verbose exit [ 1, true ]
'

Seems to be an issue with the Node bcrypt package on Windows
https://github.com/kelektiv/node.bcrypt.js/issues/442

**Comment by brylie** [comment]
It looks like that issue (bcrypt/#442) has been closed with no proposed solution. What would be some steps we can take to resolve this issue?

**Comment by tadhgpearson** [comment]
OK - it's working for me now, the fix was easy
https://stackoverflow.com/questions/29320201/error-installing-bcrypt-with-npm/29320712#29320712

Pull request coming soon ;)

**Comment by tadhgpearson** [comment]
See #106

**Comment by santisiri** [comment]
@tadhgpearson great job!

I think we must definitely prioritize Windows support right now. Wasn't aware that C++ implementation didn't properly compile there. Thanks for the Pull Request.
