### ISSUE TITLE
verifyEmail

### ISSUE THREAD

**Issue by SebastianLloret** [DemocracyEarth/sovereign#107]
Upon trying to verify a user, I get the error "Couldn't find a template named 'VerifyEmail' or 'verifyEmail'. Are you sure you defined it?

**Comment by brylie** [comment]
@SebastianLloret what steps did you take before encountering the error? We can reproduce the error by following the steps you provide.

**Comment by santisiri** [comment]
@SebastianLloret in `imports/ui/templates/layout/response/verifyEmail` you should be able to find such template. 

Also, keep in mind you should configure [MailGun](http://mailgun.com) to have an e-mail server in place for the app to work. You should find the keys to setup this on `settings.json` and the console while starting up the app must confirm keys are properly configured.

**Comment by brylie** [comment]
> keep in mind you should configure MailGun to have an e-mail server in place for the app to work. You should find the keys to setup this on settings.json and the console while starting up the app must confirm keys are properly configured.

I opened a related feature request #108

**Comment by vjrj** [comment]
Maybe its just an issue with the template name? I see "verify-email" in route.js and
```
<template name="verifyEmail">
```
in ```verifyEmail.html```

**Comment by brylie** [comment]
@vjrj will you open a PR with your fix?

**Comment by vjrj** [comment]
I was wrong, forget my previous suggestion.

**Comment by SebastianLloret** [comment]
I'm using postfix and mailutils instead of MailGun. The e-mails send out just fine, but it's the link that seems invalid. The template does indeed exist at imports/ui/templates/layout/response/verifyEmail, so I'm not sure what the issue might be.

To reproduce the error, I register a new user, go to the e-mail account, click on the link, and get the error message "Couldn't find a template named 'VerifyEmail' or 'verifyEmail'"

**Comment by vjrj** [comment]
Different results here: I've just tested with an updated master branch in local and in a real deployment, and I receive the email but the link does not show the ```verifyEmail``` template.

I get the token in the console with ```Session.get("emailToken")``` so the ```onBeforeAction``` of the route is working.

**Comment by SebastianLloret** [comment]
In the meantime, are there any other ways I could manually verify individual e-mails?

**Comment by vjrj** [comment]
@SebastianLloret try my PR...

**Comment by vjrj** [comment]
I've just deployed and tested in a production site, and works as expected:

>  Email successfully verified. Thanks!
