### ISSUE TITLE
We do not want the Facebook sign up 

### ISSUE THREAD

**Issue by fredhampton** [DemocracyEarth/sovereign#120]
We do not want the Facebook sing up.
Can you point me to where in the code I can comment out this feature 

Thanks

**Comment by medied** [comment]
Hey @fredhampton. It's in `imports/ui/templates/components/identity/login/EmailLogin.jsx`; file [looks like this](https://github.com/DemocracyEarth/sovereign/blob/master/imports/ui/templates/components/identity/login/EmailLogin.jsx). You'd have to remove line 94 (the `SocialMediaLogin` component).

Note that's for login, sign up doesn't currently show a Facebook option so you should be good there.

The other case I can think of is in the `agora.html` file, located [here](https://github.com/DemocracyEarth/sovereign/blob/master/imports/ui/templates/components/decision/agora/agora.html). Line 14 renders the social media login.

**Comment by fredhampton** [comment]
Thanks so much !!!!

**Comment by fredhampton** [comment]
@medied When I launch Sovereign as a non registered or non logged in user the the home page is blank
Is there a way to create content for the Home Page ?

**Comment by medied** [comment]
> Is there a way to create content for the Home Page ?

Probably not in an easy way like we did above with Facebook stuff. The home page not being blank is probably something that will be shipped eventually, but I'm not the best one to tell you when exactly.
