### ISSUE TITLE
How are votes allocated ?

### ISSUE THREAD

**Issue by fredhampton** [DemocracyEarth/sovereign#123]
While testing Sovereign I noted that the users I created had 1000 votes
How are the number of votes allocated ?
Is there an admin area where this can be changed ?

**Comment by santisiri** [comment]
on `lib/const.js` you will find the pre-established settings for this. The idea is to enable a liquid democracy based on the usage of tokens, so the app can be plugged to any blockchain for accountability purposes.

```
export const rules = {
  TITLE_MAX_LENGTH: 100, // length of contract titles
  MAX_TAGS_PER_CONTRACT: 6, // max amount of tags per contract
  MIN_TAGS_PER_CONTRACT: 1, // min amount.
  MAX_PROFILE_NAME_LENGTH: 20, // Maximum extension of profile name
  VOTES_INITIAL_QUANTITY: 1000, // initial votes for genesis transaction event
};
```
