### ISSUE TITLE
Is there a way to create content for the Home Page ?

### ISSUE THREAD

**Issue by fredhampton** [DemocracyEarth/sovereign#125]
When I launch Sovereign as a non registered or non logged in user the the home page is blank
Is there a way to create content for the Home Page ?

Thanks

**Comment by fredhampton** [comment]
@santisiri 
When I launch Sovereign as a non registered or non logged in user the the home page is blank
Is there a way to create content for the Home Page ?

Thanks

**Comment by santisiri** [comment]
Yes, it should be possible to display a specific `<template>` that renders content in the home. 

Check `imports/startup/client/routes.js` to configure the logic behind deciding what template to show based on the route path.
