### ISSUE TITLE
Amazon for image storage ?

### ISSUE THREAD

**Issue by fredhampton** [DemocracyEarth/sovereign#126]
Is there an option to store the member avatars locally ?
Is there an option to store member avatars on a cloud hosting service that is not Amazon ?

Thanks

**Comment by santisiri** [comment]
Hi @fredhampton, we implemented AWS for our first pilot we did with Colombia in October 2016. 

We will migrate resource storage to IPFS so we can count on the app being able to run both: as a descentralized p2p application and also able to request resources online via HTTP. 

This migration is still to be done.

**Comment by fredhampton** [comment]
Reopening this to check if there have been any changes
Is there an option to store the member avatars locally ?
Is there an option to store member avatars on a cloud hosting service that is not Amazon ?

Thanks
