### ISSUE TITLE
Basic WYSIWYG for Proposal Content

### ISSUE THREAD

**Issue by jetlej** [DemocracyEarth/sovereign#127]
It would be great to have some basic headline + bolding + linking functionality for the content body of proposals. My favorite is plugin for this is [Summernote](http://summernote.org/)

**Comment by brylie** [comment]
Summernote looks nice. Another rich text editor, for comparison, is [Quill](http://quilljs.com/).

**Comment by josiahsprague** [comment]
I'd like to advocate for something based on semantics and not visual style. Some flavor of Markdown could be very easily implemented, formatted visually, and given a WYSIWYG toolbar. Markdown is extremely popular on platforms like GitHub, reddit and Slack. In addition to being a more efficient way of formatting for those who know how to use it, Markdown provides semantic meaning in a less ambiguous way than mere visual formatting.

**Comment by josiahsprague** [comment]
Another example;

https://github.com/ianstormtaylor/slate#readme

**Comment by santisiri** [comment]
Really like the idea of WYSIWYM and been thinking on using Markdown. 

By the way: *if you highlight text* on the editor, you will find the settings for bold, italic, link, etc. The app uses a simple library called `medium-editor` which you can guess where it takes it UX inspiration from.

That said, I think migrating for markdown in the future does make sense. Right now it stores content as vanilla HTML.
