### ISSUE TITLE
Minor UI bug? - identify/profile tab wouldn't close

### ISSUE THREAD

**Issue by domingohui** [DemocracyEarth/sovereign#133]
I don't know if this is already known, intended or has been answered.. Sorry if that's the case!

Steps to reproduce:

1. Build with ```meteor npm install```
2. ```meteor npm start```
3. Create a new user
4. Login
5. Open the identify tab by clicking the avatar (if it's not already open)
6. The identity tab will not disappear even after clicking other parts of the page or the avatar on top right..

Chrome 57.0.2987.133 incognito on Mac 10.12.3

![image](https://cloud.githubusercontent.com/assets/5943822/25078819/b2368180-2304-11e7-9911-07e19127faf1.png)

**Comment by domi41** [comment]
This does not happen (anymore?) on the latest `master`, on Chromium on Debian.

**Comment by SFSandra** [comment]
@domi41 I am still having this issue - yesterday and today.
![image](https://user-images.githubusercontent.com/24529258/32413124-12f4970c-c1c8-11e7-82c2-16b684507714.png)

**Comment by bigokro** [comment]
I had the same problem. It looks like voting on something made it go away.

**Comment by aecc** [comment]
I submitted a patch, please review: https://github.com/DemocracyEarth/sovereign/pull/216
