### ISSUE TITLE
Children comments disappear on tab switch

### ISSUE THREAD

**Issue by medied** [DemocracyEarth/sovereign#135]
When commenting on a proposal, whatever is written in the comment field in children comments (not original or parent comment fields) disappear before you hit enter if you switch the browser tab. That can for sure be frustrating for a user. See image below:

<img width="788" alt="screen shot 2017-04-24 at 10 25 11 pm" src="https://cloud.githubusercontent.com/assets/4752599/25370087/2e70ac1a-293d-11e7-96bd-8792ebc4a1dd.png">

Need to make sure the comment rendering persists on tab switch

**Comment by virgile-dev** [comment]
For the time being the agora component has been scaled out to focus on core features. Hence closing
Go checkout #projectgruff in our Slack. It's a project being lead by a member of the community to enable productive debate on a web interface.
