### ISSUE TITLE
"Search tags..." is considered as an available tag

### ISSUE THREAD

**Issue by vntrp** [DemocracyEarth/sovereign#141]
![screenshot 2017-04-25 02 03 21](https://cloud.githubusercontent.com/assets/12161094/25372541/78a3baca-295b-11e7-9626-3b312c8d3ff4.png)

It's possible to tag a draft with the tag "Search tags...", which doesn't really makes sense.

**Comment by domi41** [comment]
Nice catch ! Did you type `Search tags…` by hand or was it never removed ?
We can also add empty tags, or tags with only spaces...

This issue can be easily wrapped in a Gherkin Scenario.

**Comment by virgile-dev** [comment]
Tags have been replaced by hashtags. Closing
