### ISSUE TITLE
Nationality can't be selected or saved

### ISSUE THREAD

**Issue by vntrp** [DemocracyEarth/sovereign#142]
![screenshot 2017-04-25 02 08 03](https://cloud.githubusercontent.com/assets/12161094/25372717/21792e50-295c-11e7-97fa-1a371e4bd008.png)

We can't modify the nationality, and we can't save it either.
What is the frame below "Nationality"? is it for automatic detection and selection of nationality?

**Comment by virgile-dev** [comment]
I remember we had a similar problem with @vjrj, it's because of url setup. The app is supposed to run with https, but alpha.democracy.earth doesn't, hence nationality selection isn't working. @santisiri

**Comment by herbstephens** [comment]
Same. Tried to save "French"...but when hit "Save Profile"..box closed..and didn't save nationality.
