### ISSUE TITLE
Draft are saved but not displayed on "/feed?stage=draft&kind=vote"

### ISSUE THREAD

**Issue by virgile-dev** [DemocracyEarth/sovereign#144]
Here are a few drafts I haven't published to vote : 
- http://alpha.democracy.earth/vote/test-draft
- http://alpha.democracy.earth/vote/test-draft-2

But they don't show on http://alpha.democracy.earth/feed?stage=draft&kind=vote, so people can't edit them with me :(
<img width="1156" alt="capture d ecran 2017-04-25 a 09 59 13" src="https://cloud.githubusercontent.com/assets/11473995/25374473/ddb05cba-299d-11e7-9648-49b98b6731fc.png">

**Comment by medied** [comment]
Related to #146 regarding the feed menu

**Comment by virgile-dev** [comment]
No longer relevant since refactoring
