### ISSUE TITLE
ON / OFF Multiple choice switch doesn't work

### ISSUE THREAD

**Issue by virgile-dev** [DemocracyEarth/sovereign#145]
Even if switched off I can add alternatives
<img width="778" alt="capture d ecran 2017-04-25 a 10 01 04" src="https://cloud.githubusercontent.com/assets/11473995/25374573/385b096c-299e-11e7-93f9-82a4bb8dbe5a.png">

**Comment by medied** [comment]
Related to #161

**Comment by virgile-dev** [comment]
Multiple choices has been scaled out.
