### ISSUE TITLE
Participation feed doesn't show topics on which I participated

### ISSUE THREAD

**Issue by virgile-dev** [DemocracyEarth/sovereign#146]
Here are a few topics I voted / commented on : 
http://alpha.democracy.earth/vote/quick-one---vote-yes
http://alpha.democracy.earth/vote/quick-one-2---vote-no
http://alpha.democracy.earth/vote/idea-without-a-vote

But here is what my feed looks like on : http://alpha.democracy.earth/feed?stage=live&kind=vote&peer=Virgile
<img width="1247" alt="capture d ecran 2017-04-25 a 10 05 07" src="https://cloud.githubusercontent.com/assets/11473995/25374694/ae151daa-299e-11e7-8acc-9df5d8d6f158.png">

**Comment by herbstephens** [comment]
Same issue.

**Comment by medied** [comment]
Related to #167 regarding the feed menu
