### ISSUE TITLE
We are interested in testing DemocracyEarth on some internal Coop initiatives. 

### ISSUE THREAD

**Issue by fredhampton** [DemocracyEarth/sovereign#149]
We are interested in testing DemocracyEarth on some internal Coop initiatives. 
Is the Master Branch ready for this kind of testing ?

**Comment by domi41** [comment]
Hello !

You can [follow the monthly activity](https://github.com/DemocracyEarth/sovereign/pulse/monthly) of the repository ; these kinds of projects (the pioneer ones, especially community-driven) are especially hard to schedule, as they're unique and treading uncharted lands without roads. This being said, what I gather from following this project is that it is closing in on its first release. _The last mile is usually the toughest._ The core features (authoring/voting/delegating/debating) are almost here, and a feature freeze for the refactor/bughunt/cleanup phase should soon follow. As you can see from [the contributions graph](https://github.com/DemocracyEarth/sovereign/graphs/contributors), the activity was boosted around (and perhaps _by_) the recent USA presidential elections, as there was a lot of controversy about the integrity and reliability of said elections. You should subscribe to [the newsletter](http://democracy.earth/), and you can preview the [alpha demo here](http://alpha.democracy.earth/).

**Comment by fredhampton** [comment]
Thanks !!!
I just checked out the alpha...Wondering why the tight integration with FB ?

**Comment by domi41** [comment]
Ideally sovereign should support all OpenID providers ; FB probably got prime time because one of the points of making a prototype is to buzz on social networks, to conscientize about the very idea of liquid democracy.

Still, it is optional, I never used the feature myself.

Sorry for the long answer delay, and keep on your toes, sovereign can't be released soon enough !
