### ISSUE TITLE
When newly proposed idea is "unavailable"...cannot go to existing idea

### ISSUE THREAD

**Issue by herbstephens** [DemocracyEarth/sovereign#151]
![unavailable](https://cloud.githubusercontent.com/assets/11063638/25401705/4b5f3bf2-29ab-11e7-88c7-0b7707891f84.png)

**Comment by herbstephens** [comment]
alpha.democracy.earth/vote/should-france-exit-eu

**link should take me to existing proposal**

**Comment by virgile-dev** [comment]
This doesn't work this way anymore, closing .
