### ISSUE TITLE
Allow sorting of comments from most recent to least recent

### ISSUE THREAD

**Issue by SFSandra** [DemocracyEarth/sovereign#152]
right now comment threads go from oldest to most recent, so most recent are on bottom and oldest are on top

would be good to resort so most recent comments on top

**Comment by domi41** [comment]
The comments structure is a graph. How do you envision handling recent children comments without losing their context ? Only sort root comments ?

**Comment by virgile-dev** [comment]
For the time being the agora component has been scaled out to focus on core features. Hence closing
Go checkout #projectgruff in our Slack. It's a project being lead by a member of the community to enable productive debate on a web interface.
