### ISSUE TITLE
Allow adjustment of invested votes' count in the confirmation modal

### ISSUE THREAD

**Issue by SFSandra** [DemocracyEarth/sovereign#153]
when placing a vote, it would be great if the the pop-up window allowed me to adjust # of tokens. Instead I have to select "Not Now" and adjust the votes on the slider and submit again.   Could we add a button to that pop up window: 

Vote
Not Now
**Adjust**

![place vote comm window](https://cloud.githubusercontent.com/assets/24529258/25407600/bb185258-29bf-11e7-9e39-ace02ac4e781.png)

**Comment by virgile-dev** [comment]
That's a good idea !
