### ISSUE TITLE
Reposition of "Publish Idea" Button

### ISSUE THREAD

**Issue by SFSandra** [DemocracyEarth/sovereign#156]
1. The search proposal box appears above the 'publish idea' button (example below)...

![for santi](https://cloud.githubusercontent.com/assets/24529258/25414170/c9650e44-29e4-11e7-8a1a-3859b44b6620.png)

2. ...I found it confusing - while creating the ballot for Should we Rename Sovereign, I somehow imported the ballot for the Magna Carta question (example below) drat!
![mistake](https://cloud.githubusercontent.com/assets/24529258/25414008/9062b07a-29e3-11e7-97cb-12b4c8f65158.png)

**Comment by virgile-dev** [comment]
UI has changed a lot since refactoring hence closing.
