### ISSUE TITLE
On iPhone 7 - Safari - this is all I can open, no further links

### ISSUE THREAD

**Issue by dwightmwilson** [DemocracyEarth/sovereign#159]
![dem earth mobile view](https://cloud.githubusercontent.com/assets/28016364/25459508/67cd923c-2a93-11e7-8458-526b1787f1c7.png)

**Comment by medied** [comment]
Seems to be related to #155

**Comment by virgile-dev** [comment]
@medied is this solved ?

**Comment by santisiri** [comment]
Old
