### ISSUE TITLE
No Multiple Choice - can't create multiple choice options

### ISSUE THREAD

**Issue by SFSandra** [DemocracyEarth/sovereign#161]
per snip below, we can select enable mc but cannot create options on the ballot, only Yes/No possible. Assume that's by (no) design....

![mc hammer](https://cloud.githubusercontent.com/assets/24529258/25466360/08e2a3c8-2abd-11e7-8485-74604019cbcf.png)

**Comment by virgile-dev** [comment]
No longer relevant since refactoring.
