### ISSUE TITLE
Can't sign up w/ Facebook

### ISSUE THREAD

**Issue by SFSandra** [DemocracyEarth/sovereign#163]
here is the pop up I get when I try

![fb](https://cloud.githubusercontent.com/assets/24529258/25466533/1b86eb6e-2abe-11e7-9b34-91d9e301955b.png)

**Comment by virgile-dev** [comment]
This was fixed but the bug has return. Now it's the application  that is missing configuration.
![Capture d’écran 2018-03-03 à 12.12.44.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a4cd03330957c0012d7570d/125516c66e82c728ace21e0d46cb958a379791accfed3da35d585c752a54267d6956f37a28c8b37bf21228410ea3febc405a4145fee78d2fb4aa2e30c80351b882294d7ed43840a5e9854dbe00bf76de4d85e3bc8a4d92b96c73b2d88f5d220c4749d7ab0268f9d31e8a4afc59e0445fa5163463e671337a479118732e792a.png)
