### ISSUE TITLE
Slider is not sensitive enough - jumps from 10 votes to 12 votes

### ISSUE THREAD

**Issue by SFSandra** [DemocracyEarth/sovereign#164]
I can't vote 11 times - slider is not sensitive enough. 

![10 votes placed](https://cloud.githubusercontent.com/assets/24529258/25467861/30af8002-2ac6-11e7-877d-d62d3a90b42b.png)

**Comment by SFSandra** [comment]
Virgile made the same observation on the vote I created "Vote No 11 Times" (to prove that you cannot, or it is too difficult...same thing)

**Comment by virgile-dev** [comment]
#202 will tackle just that.

**Comment by medied** [comment]
Closing to focus on #202
