### ISSUE TITLE
Delegation of Votes Slider

### ISSUE THREAD

**Issue by SFSandra** [DemocracyEarth/sovereign#171]
Not sure what this continuum is anchored by on the left and right? How does it show how many votes have been placed/are available? 

![image](https://cloud.githubusercontent.com/assets/24529258/25637043/513e09ee-2f38-11e7-9267-94092fe9c3fc.png)

**Comment by virgile-dev** [comment]
This UI component has changed a lot closing. I think this problem has been solved.
