### ISSUE TITLE
"Publish Idea" box stays on screen after hitting Publish (chrome on iPad Pro)

### ISSUE THREAD

**Issue by herbstephens** [DemocracyEarth/sovereign#173]
![img_0552](https://cloud.githubusercontent.com/assets/11063638/25687867/97706d7a-302e-11e7-9231-7216a33dde31.PNG)

**Comment by domi41** [comment]
Is there a way to see the javascript's console on Chrome on iPad ?

**Comment by virgile-dev** [comment]
We got rid of this modal a few month ago. Hence closing
