### ISSUE TITLE
To Create a Plugin in the in Windows for Processmaker

### ISSUE THREAD

**Issue by jemiris** [DemocracyEarth/sovereign#176]
**************************************************************************
  ****# To Create a Plugin in the in Windows for Processmaker****
**************************************************************************
Step :1
============
Main Steps to Plugins can not be created on Windows servers, because Windows does not support symbolic links; however, there is an experimental script for Windows servers available at <INSTALL-DIRECTORY>/workflow/engine/gulliver-win.bat which can be tested. .
http://wiki.processmaker.com/3.0/Plugin_Development

C:\Bitnami\processmaker-3.1-1\apps\processmaker\htdocs\workflow\engine>gulliver-win.bat new-plugin deleteCases

using DSN Connection
The plugin deleteCases exists in this file C:\Bitnami\processmaker-3.1-1\apps\pr
ocessmaker\htdocs\workflow\engine\plugins\deleteCases\class.deleteCases.php
**************************************************************************
Step :2
============
Do you want to create a new plugin? [Y/n]y

creating plugin directory C:\Bitnami\processmaker-3.1-1\apps\processmaker\plugin
s\deleteCases

saved 387 bytes in file deleteCases\setup.xml [pluginSetup.xml]
saved 183 bytes in file deleteCases\messageShow.xml [pluginMessageShow.xml]
saved 3056 bytes in file deleteCases\config\schema.xml [pluginSchema.xml]
saved 2067 bytes in file deleteCases\config\propel.ini [pluginPropel.ini]
saved 2061 bytes in file deleteCases\config\propel.mysql.ini [pluginPropel.mysql
.ini]
**************************************************************************
Step :3
============
Change system logo [y/N]y

saved 750 bytes in file public_html\deleteCases.png [deleteCases.png]
Create an example Page [Y/n]y
saved 151 bytes in file deleteCases\menudeleteCases.php [pluginMenu]
saved 932 bytes in file deleteCases\deleteCasesApplication.php [pluginApplicatio
n.php]
saved 45 bytes in file deleteCases\deleteCasesApplication.html [pluginApplicatio
n.html]
saved 6518 bytes in file deleteCases\deleteCasesApplication.js [pluginApplicatio
n.js]
saved 1519 bytes in file deleteCases\deleteCasesApplicationAjax.php [pluginAppli
cationAjax.php]
**************************************************************************
Step :4
============
Create new option in the menu of cases [Y/n]y

saved 2384 bytes in file deleteCases\menuCasesdeleteCases.php [pluginMenuCases]
saved 547 bytes in file deleteCases\deleteCasesApplication2.php [pluginApplicati
on2.php]
saved 45 bytes in file deleteCases\deleteCasesApplication2.html [pluginApplicati
on2.html]
saved 7599 bytes in file deleteCases\deleteCasesApplication2.js [pluginApplicati
on2.js]
saved 547 bytes in file deleteCases\deleteCasesApplication3.php [pluginApplicati
on3.php]
saved 45 bytes in file deleteCases\deleteCasesApplication3.html [pluginApplicati
on3.html]
saved 565 bytes in file deleteCases\deleteCasesApplication3.js [pluginApplicatio
n3.js]
**************************************************************************
Step :5
============
Create the Role 'PROCESSMAKER_DELETECASES' and
       the Permission 'PM_DELETECASES' [y/N]y
**************************************************************************
Step :6
============	   
Create a Redirect Login for the Role 'PROCESSMAKER_DELETECASES' [y/N]y
**************************************************************************
Step :7
============
Create external step for Processmaker [y/N]y

saved 1042 bytes in file deleteCases\stepdeleteCasesApplication.php [pluginStepA
pplication.php]
saved 45 bytes in file deleteCases\stepdeleteCasesApplication.html [pluginStepAp
plication.html]
saved 2707 bytes in file deleteCases\stepdeleteCasesApplication.js [pluginStepAp
plication.js]
saved 740 bytes in file deleteCases\stepdeleteCasesApplicationAjax.php [pluginSt
epApplicationAjax.php]
**************************************************************************
Step :8
============
Create an element for the Processmaker Dashboards [y/N]y

saved 3702 bytes in file deleteCases\classes\class.dashletdeleteCases.php [plugi
nDashletClass.php]
saved 1788 bytes in file pluginDashlet.html
**************************************************************************
Step :9
============
Create a PmFunction Class for extending Processmaker [y/N]y

saved 484 bytes in file deleteCases\classes\class.pmFunctions.php [class.pmFunct
ions.php]
saved 3089 bytes in file deleteCases.php [pluginMainFile]
saved 384 bytes in file deleteCases\class.deleteCases.php [pluginClass]
**************************************************************************
Step :10
============
Press any key to continue . . .

C:\Bitnami\processmaker-3.1-1\apps\processmaker\htdocs\workflow\engine>

**Comment by domi41** [comment]
Hello !

How is that related to *sovereign*, and what are these PHP files ?
