### ISSUE TITLE
kernel hugepages

### ISSUE THREAD

**Issue by ajax-2** [DemocracyEarth/sovereign#182]
I cannot get hugepages that i need ,but the system have enough memory, i can be sure

**Comment by domi41** [comment]
Hello @ajax-2 !
Can you describe what you did and what went wrong ? You can also use the [Issue Template](https://github.com/DemocracyEarth/sovereign/blob/master/ISSUE_TEMPLATE.md).

**Comment by ajax-2** [comment]
my system memory is 16G, and aviliable memory is 15G after booting .Then  i set hugepages=1G and hugepage-number=14 , but i only get 13 pages. however i can set hugepages=2M and hugepage-number=7168 . so i don't know what is reason . thank you for reply me

**Comment by domi41** [comment]
@ajax-2 Seems OK to me. Do you know what hugepages are for ? How is this related to sovereign ?

**Comment by ajax-2** [comment]
my opinion, hugepages is a memory block to improve the velocity of memory accessing, and it will be allocated before using system,so we need set it in a boot-file. example grup.conf or pxelinux.cfg . But i don't know how we get  ,such as begin-address in kernel ,whether address is continous or not

**Comment by domi41** [comment]
Each hugepage may be used only by one process ? That would explain the 13. How is any of this related to sovereign, again ?

**Comment by domi41** [comment]
Maybe we should close this. Unsure _what_ to call these kinds of issues, though.
