### ISSUE TITLE
Closing of the identity tap

### ISSUE THREAD

**Issue by Phieldar** [DemocracyEarth/sovereign#186]
After having created an identity, the tab won't close. I'm on Ubuntu 17.04, on Firefox.

**Comment by julianmnst** [comment]
Same here.

**Comment by medied** [comment]
Related to #133

**Comment by domi41** [comment]
Can anyone reproduce this bug with the javascript console open, and dump the log ?

**Comment by SFSandra** [comment]
I am unable to close the identity tap on the desktop version 
![image](https://user-images.githubusercontent.com/24529258/32413120-fa3abc64-c1c7-11e7-8ad6-25e465e89f95.png)

**Comment by jlr13** [comment]
Had the same issue yesterday, browser reload fixed it.

**Comment by votedave** [comment]
same issue - Win 7 - 64, chrome Version 62.0.3202.75 (Official Build) (64-bit)
![se user info](https://user-images.githubusercontent.com/17741338/32421274-adf4bb7e-c2d1-11e7-8066-3805965f53df.JPG)

**Comment by aecc** [comment]
I submitted a patch, please review: https://github.com/DemocracyEarth/sovereign/pull/216
