### ISSUE TITLE
Results display flashing

### ISSUE THREAD

**Issue by SFSandra** [DemocracyEarth/sovereign#187]
Tried to Vote on proposal ICO Yes or No but Results bar wouldn't load.

![image](https://user-images.githubusercontent.com/24529258/27709744-1df5e6ac-5cd2-11e7-9bde-919519040f1c.png)

**Comment by virgile-dev** [comment]
Yup I have this issue too : 
![flashing ballot](https://im2.ezgif.com/tmp/ezgif-2-6c17f41466.gif)

Tested on chrome : Version 59.0.3071.115

**Comment by domi41** [comment]
We can see this as well. Meanwhile, the server is logging tons of 

```
[getServerTime] date request : Thu Sep 14 2017 21:01:04 GMT+0200 (CEST)
```

**Comment by roipoussiere** [comment]
On alpha.democracy.earth, the date is also flashing, passing from today to yesterday few times per second. Is is linked ?

**Comment by santisiri** [comment]
This is from a deprecated version of Democracy Earth.
