### ISSUE TITLE
Unable to vote on proposal by Penny Lane

### ISSUE THREAD

**Issue by SFSandra** [DemocracyEarth/sovereign#188]
voting buttons (Yes, No) unresponsive 

![image](https://user-images.githubusercontent.com/24529258/27709929-c6165768-5cd2-11e7-9232-1cd6dde8f82c.png)

**Comment by domi41** [comment]
Sometimes, the page crashes, and buttons stop responding. When that happens, please dump the javascript console log into the issue report. Closing this unless someone can reproduce this issue.
