### ISSUE TITLE
Upvote and downvote arrow for comment don't display

### ISSUE THREAD

**Issue by virgile-dev** [DemocracyEarth/sovereign#193]
Tested on chrome : Version 59.0.3071.115

<img width="1416" alt="capture d ecran 2017-07-31 a 12 06 49" src="https://user-images.githubusercontent.com/11473995/28773172-c9ff17aa-75e8-11e7-8053-a358dd6e3fe2.png">

**Comment by thatsVishal** [comment]
Can you tell me where is the file location?

**Comment by domi41** [comment]
We don't see that bug on chrome on the latest master. We cannot use them, as per #35, but they show up.
