### ISSUE TITLE
Login doesn't work

### ISSUE THREAD

**Issue by virgile-dev** [DemocracyEarth/sovereign#195]
# This is a Bug Report
 #### :tophat: Description
 
 * What went wrong?
Impossible to login
 * What did you expect should have happened?
Entering email, password click "Sign in" to be logged in.
 * What was the config you used?
http://alpha.democracy.earth/
 * What stacktrace or error message from your provider did you see?
 Navigator console shows : 
Failed to load resource: net::ERR_CONNECTION_CLOSED /data/geo.json Failed to load resource: net::ERR_CONNECTION_CLOSED
TypeError: Cannot read property 'data' of undefined e0757bc4b5786945e4c97c819cc0bdc309896fdf.js?meteor_js_resource=true:272 Uncaught 
    at e0757bc4b5786945e4c97c819cc0bdc309896fdf.js?meteor_js_resource=true:272
    at e0757bc4b5786945e4c97c819cc0bdc309896fdf.js?meteor_js_resource=true:204
    at e0757bc4b5786945e4c97c819cc0bdc309896fdf.js?meteor_js_resource=true:1
    at XMLHttpRequest.y.onreadystatechange (e0757bc4b5786945e4c97c819cc0bdc309896fdf.js?meteor_js_resource=true:204)
 
 #### :clipboard: Additional Data
 
 * ***Sovereign deployment where you found the issue***:
http://alpha.democracy.earth/
 * ***Browser & version***:
Version 60.0.3112.90
 * ***URL to reproduce the error***: http://alpha.democracy.earth/

**Comment by domi41** [comment]
We cannot reproduce this with the current version. Please re-open if you can, and with which browser.
