### ISSUE TITLE
Skype-  Get E-mail ID of the user

### ISSUE THREAD

**Issue by anirudhaditya** [DemocracyEarth/sovereign#199]
We are using Skype and Skype for business as our bot channel. We are facing issue in getting who has logged in the Skype. Basically trying to get the email Id of the logged in user while 5he conversation starts. Now we get only the display name and nothing beyond that. 

Any help, 

Thanks
Ani

**Comment by domi41** [comment]
Hello ! How is that related to `sovereign` ?

**Comment by anirudhaditya** [comment]
Not sure what you have asked @Domi.

My question is how bot would know who has logged in to Skype. We want to get the userID of the logged in user. 

Similar way we get the mobile no# for SMS.

**Comment by anirudhaditya** [comment]
Oh...am in wrong window. Sorry Dominant.
