### ISSUE TITLE
Unresponsive 'Publish Idea' button 

### ISSUE THREAD

**Issue by medied** [DemocracyEarth/sovereign#200]
# This is a Bug Report

#### :tophat: Description

For bug reports:
* What went wrong?
'Publish Idea' button is unresponsive when creating a proposal. It simply doesn't become active after filling out required fields. I created a fresh `git clone`, `npm install`, and got meteor v1.5.1
* ~~What did you expect should have happened?~~
* What was the config you used?
Meteor v1.5.1, running a regular local deploy
* ~~What stacktrace or error message from your provider did you see?~~

#### :clipboard: Additional Data

* ~~***Sovereign deployment where you found the issue***:~~
* ***Browser & version***:
Latest Chrome
* ~~***Screenshot***~~:
* ~~***Error messages***~~:
* ~~***URL to reproduce the error***~~:

**Comment by medied** [comment]
@santisiri do you see this same behavior from your end? Checked in with @virgile-dev and he also sees the same behavior. Seems the [alpha](http://alpha.democracy.earth/) version is working fine. Also, I was seeing this behavior before commit 7d9b756a413b7380a3ea47216566112a0e08fa50

**Comment by domi41** [comment]
I think I had the same issue, and fixed it in #198 .
It's a desktop-only issue, if memory serves.

**Comment by medied** [comment]
Hey @domi41 yeap, was literally just looking into that when you commented. Looks like `rightToVote` is causing the issue, which is [involved](https://github.com/DemocracyEarth/sovereign/pull/198/files#diff-9789b93e1f9378a8dfaa2fbf4d9fa3b9) in #198 as you mention. Will continue debugging

**Comment by medied** [comment]
`rightToVote` is never getting set because the code that does so was commented out in commit 0c6c0982a654b25b075e8d6b655636016560ae82. 

`imports/startup/client/functions.js`

```
// status of action button
    if (contract.kind === 'DELEGATION') {
      Session.set('rightToVote', verifyDelegationRight(contract.signatures));
    } else if (contract.kind === 'VOTE' && contract.stage === 'DRAFT') {
      Session.set('rightToVote', true);
      Session.set('alreadyVoted', false);
    } else if (contract.kind === 'VOTE' && contract.stage === 'LIVE') {
      Session.set('rightToVote', true);
      Session.set('alreadyVoted', verifyVotingRight(contract._id));
    } else if (contract.kind === 'VOTE' && contract.stage === 'FINISH') {
      Session.set('rightToVote', false);
    }
```

@santisiri will wait to hear from you because I don't want to interfere with what was started in that commit. But FYI this is sort of a blocker because it inhibits testing for development. I will uncomment and test forth, but probably best to wait before a PR?

**Comment by medied** [comment]
Not an issue anymore as code has been refactored
