### ISSUE TITLE
Delegations not looking so hot on mobile

### ISSUE THREAD

**Issue by virgile-dev** [DemocracyEarth/sovereign#204]
# This is a Bug Report

#### :tophat: Description
Delegation are very clear on desktop
<img width="866" alt="capture d ecran 2017-10-18 a 22 13 48" src="https://user-images.githubusercontent.com/11473995/31740435-a864fa2c-b451-11e7-9f5d-5cf8b890846e.png">

But on mobile we don't really understand what's happened
<img width="264" alt="capture d ecran 2017-10-18 a 22 11 30" src="https://user-images.githubusercontent.com/11473995/31740461-baec3ae8-b451-11e7-9b3f-762963ccd8c4.png">

Probably centering the 2 avatars and user names and putting the arrow from top to bottom would fix it :)

**Comment by santisiri** [comment]
Fixed this. Now they look great.
