### ISSUE TITLE
Hamburger menu button fails to render sometimes

### ISSUE THREAD

**Issue by medied** [DemocracyEarth/sovereign#206]
<img width="506" alt="screen shot 2017-10-24 at 9 47 59 pm" src="https://user-images.githubusercontent.com/4752599/31976366-27df8b2a-b905-11e7-9dc8-3f825727fe9d.png">

Mobile rendering was blocked by left column, I was unable to hide it and view posts normally. After playing around it for a while I realized the hamburger was missing, it would come and go after consecutive random refreshes. 

<img width="466" alt="screen shot 2017-10-24 at 9 51 16 pm" src="https://user-images.githubusercontent.com/4752599/31976521-04b5d93c-b906-11e7-94a0-a6f2b9103120.png">

You seen this before?

**Comment by santisiri** [comment]
You probably refreshed to mobile coming from a desktop rendering in your local instance. This shouldn't happen on a non-dev environment.

**Comment by medied** [comment]
Yea looks like this is fine now 👍
