### ISSUE TITLE
App log-in not working

### ISSUE THREAD

**Issue by SFSandra** [DemocracyEarth/sovereign#207]
# This is a Bug Report
#### :tophat: social app sign in not working

For bug reports:
* Received an error screen and failed to log in
* logged in via my FB account
* using desktop message
* App Not Setup: This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions.

* ***dt version 0.1***:
* ***Chrome Version 61.0.3163.100***:
* ***Screenshot
![image](https://user-images.githubusercontent.com/24529258/32136924-f9686d42-bbcb-11e7-8ddb-47430842cd47.png)
***:
* ***App Not Setup: This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions.***:
* ***https://vote.democracy.earth/***:

**Comment by medied** [comment]
I was able to replicate this issue from my end. @santisiri maybe try the following?

https://stackoverflow.com/questions/30085246/app-not-setup-this-app-is-still-in-development-mode
