### ISSUE TITLE
Mobile popup unresponsive 

### ISSUE THREAD

**Issue by medied** [DemocracyEarth/sovereign#208]
# This is a Bug Report

#### :tophat: Description

Popup links are unresponsive on mobile (iPhone or Android). Popup renders fine and input text fields are working, it's just the button and link to sign up and recover password.

**Comment by santisiri** [comment]
@medied been looking into this, definitely seems like a `react` specific thing. Please check this out as soon as possible.

**Comment by medied** [comment]
Yeap, started toying with it last night. Let's talk in #209
