### ISSUE TITLE
Profile Tooltip not functioning as expected

### ISSUE THREAD

**Issue by AlexJupiter** [DemocracyEarth/sovereign#211]
# This is a Bug Report 

#### :tophat: Description

For bug reports:
* The profile tooltip cannot be collapsed after signing up with Facebook
* I expected the tooltip to to close when I clicked elsewhere on the screen, or on the profile pic
* I used Chrome, on OSX, V61
* Couldn't get error from Chrome (seemed to bug out the browser window), however got this error message from Safari:
![image](https://user-images.githubusercontent.com/7900773/32415789-516396e0-c237-11e7-9563-d888934d18e7.png)

#### :pushpin: Related issues
* #010101

#### :clipboard: Additional Data

* ***Sovereign deployment where you found the issue***: 14:40pm GMT Sun 5th Nov 
* ***Browser & version***: Chrome V61, OSX
* ***Screenshot***:
![image](https://user-images.githubusercontent.com/7900773/32415796-7afa77c6-c237-11e7-8715-d503887e3012.png)
* ***Error messages***:
![image](https://user-images.githubusercontent.com/7900773/32415789-516396e0-c237-11e7-9563-d888934d18e7.png)
* ***URL to reproduce the error***: vote.democracy.earth

**Comment by votedave** [comment]
same issue as reported lower in the list.

**Comment by santisiri** [comment]
Fixed in the last release, all calls to Facebook are n ow made via HTTPS.
