### ISSUE TITLE
Burger Menu Fails To Open on Mobile (Safari iPhone)

### ISSUE THREAD

**Issue by AlexJupiter** [DemocracyEarth/sovereign#212]
# This is a Bug Report 

#### :tophat: Description

For bug reports:
* What went wrong?
I cannot open the burger menu (or it takes about five seconds to open) on iOS Safari

* What did you expect should have happened?
The burger menu should open the left hand nav panel

* What was the config you used?
Safari on iOS 11.1

* What stacktrace or error message from your provider did you see?

#### :clipboard: Additional Data

* ***Sovereign deployment where you found the issue***: 15:00 GMT Sun 5th Nov
* ***Browser & version***: Safari iOS 11.1
* ***Screenshot***:
* ***Error messages***:
* ***URL to reproduce the error***: vote.democracy.earth

**Comment by santisiri** [comment]
This should be fixed in the last release `1.0.3-alpha`. Thanks.
