### ISSUE TITLE
Screen freezes after I cast vote (desktop)

### ISSUE THREAD

**Issue by dwightmwilson** [DemocracyEarth/sovereign#214]
# This is a (Bug Report / Feature Proposal)

#### :tophat: Description

For bug reports:
* What went wrong?
after voting my screen would not reload unable to see delegates, unable to get to poll feed
* What did you expect should have happened?
I expected to be able to see a list of Sovereign members on the left of my screen, and a feed of proposals on the main screen
* What was the config you used?
on a MacBook Air, in the web app through a Chrome browswer

* What stacktrace or error message from your provider did you see?
none

![image](https://user-images.githubusercontent.com/24529258/35538520-11bc513a-0503-11e8-884c-699cbbd2ab7c.png)

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

#### :pushpin: Related issues
* #010101

#### :clipboard: Additional Data

* ***Sovereign deployment where you found the issue***:
* ***Browser & version***:
* ***Screenshot***:
* ***Error messages***:
* ***URL to reproduce the error***:

**Comment by santisiri** [comment]
Yes, we aware of this. Will be fixed soon.

**Comment by SFSandra** [comment]
I added detail and updated this bug report issue b/c it is exactly the same problem I am encountering today, January 28, 2018.
