### ISSUE TITLE
The profile box with the country's name doesn't load everything

### ISSUE THREAD

**Issue by nelruk** [DemocracyEarth/sovereign#215]
Part of the name of my country is missing 

![gyazo](https://user-images.githubusercontent.com/5068576/32689470-53866e3e-c6c4-11e7-85aa-f00aef11ddf7.png)

**Comment by santisiri** [comment]
This is really strange, will look into it.

**Comment by virgile-dev** [comment]
This looks like it's been fixed. Closing !
