### ISSUE TITLE
Voting result doesn't always show up

### ISSUE THREAD

**Issue by virgile-dev** [DemocracyEarth/sovereign#221]
# This is a Bug Report 

#### :tophat: Description

For bug reports:
* What went wrong? : It doesn't show the percentage in favor and against. (and really wanna how that vote turns out.) It looks like the bug occurs when a ballot has a closing date.

#### :clipboard: Additional Data

* ***Sovereign deployment where you found the issue***: https://vote.democracy.earth/
* ***Browser & version***: Chrome
* ***Screenshot***:
![capture d ecran 2017-11-16 a 18 00 01](https://user-images.githubusercontent.com/11473995/32908526-1f173996-cb04-11e7-952a-052a03ecd0bc.png)
![capture d ecran 2017-11-16 a 19 28 53](https://user-images.githubusercontent.com/11473995/32908650-7130344e-cb04-11e7-9285-e7b3954d690f.png)

**Comment by nicktobolski** [comment]
Is this actually a bug? Or functioning as intended? Looking for ways to help.

**Comment by virgile-dev** [comment]
This has been revamped with the always on decision process. Results display in real time, they are never closed and they show the number of voters in the top right corner. I'm closing this for now.
