### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by paulamlb** [DemocracyEarth/sovereign#229]
# This is a (Bug Report / Feature Proposal)

#### :tophat: Description

For bug reports:
* What went wrong? When trying to access Sovereign today, for the past 30 min, I've been getting this screen 
<img width="1277" alt="screen shot 2018-01-30 at 12 54 54" src="https://user-images.githubusercontent.com/18194034/35572966-f202244a-05bc-11e8-978f-49896fac6338.png">

* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

#### :pushpin: Related issues
* #010101

#### :clipboard: Additional Data

* ***Sovereign deployment where you found the issue***:
* ***Browser & version***:
* ***Screenshot***:
* ***Error messages***:
* ***URL to reproduce the error***:

**Comment by domi41** [comment]
It's back on. Thanks ! Closing…

**Comment by votedave** [comment]
![image](https://user-images.githubusercontent.com/17741338/55372870-c0ee9680-5535-11e9-92df-ca53b7275bfa.png)
2 days, consistent denial. What's up?
