### ISSUE TITLE
unable to post proposal

### ISSUE THREAD

**Issue by SFSandra** [DemocracyEarth/sovereign#230]
# This is a Bug Report

#### :tophat: Description

For bug reports:
* What went wrong? I typed in my proposal but was unable to submit it  - no response when I clicked the "clipboard" icon

* What did you expect should have happened?
I expected, from previous experience, for another click to post my proposal. Before, I could choose a date to close, or leave always on - THEN post the proposal.  

* What was the config you used?  web app, chrome browser from a MacBook Air

* What stacktrace or error message from your provider did you see? no message, just frozen screen

#### :pushpin: Related issues
* #010101

#### :clipboard: Additional Data

* ***Sovereign deployment where you found the issue***: https://vote.democracy.earth/
* ***Browser & version***: Google Chrome Version 63.0.3239.132 (Official Build) (64-bit)
* ***Screenshot***:![image](https://user-images.githubusercontent.com/24529258/35757047-571bf722-0822-11e8-9f40-ce5e2eaf3825.png)
* ***Error messages***: none
* ***URL to reproduce the error***:

**Comment by virgile-dev** [comment]
This looks like it's working now. Closing this for now.
