### ISSUE TITLE
Blockstack login doesn't work anymore

### ISSUE THREAD

**Issue by virgile-dev** [DemocracyEarth/sovereign#240]
Bug visible @ vote.democracy.earth

**Comment by herbstephens** [comment]
![image](https://user-images.githubusercontent.com/11063638/44225015-19a52680-a141-11e8-8660-ce06eb65301e.png)

Just FYI .. Blockstack login still not working. [sure you are aware .. but was just diving into Blockstack a bit and testing...
 
Also, per image above .. given "?" in blue box .. seems the DEF logo is missing from configuration.
