### ISSUE TITLE
Restful API

### ISSUE THREAD

**Issue by virgile-dev** [DemocracyEarth/sovereign#241]
For this task, we have standard [HTTP response status codes](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status) and some [best practices](https://blog.risingstack.com/10-best-practices-for-writing-node-js-rest-apis/) in order to follow some guides

The main point here is to choose a web framework, we have [koa](http://koajs.com/) and [express](http://expressjs.com/) as the top candidates.

**Koa**
- ES2015/ES2017 and async function support
- TJ Holowaychuk (express author)
- 20k stars + 21 opencollective backers

**Express**
- ES5
- IBM
- 37k stars

**Comment by virgile-dev** [comment]
@LucasIsasmendi could you start outlining tasks to start tackling this ?

**Comment by LucasIsasmendi** [comment]
Skeleton is almost ready. Will be release soon in repo `sovereign-restful-api`

**Comment by LucasIsasmendi** [comment]
@santisiri  the API is in the [sovereign-restful-api](https://github.com/DemocracyEarth/sovereign-restful-api) repo. Is a node.js server with express connected to sovereign database. Readme in `master` branch is pending. All the apidoc documentation is in `gh-pages` branch.

**Comment by santisiri** [comment]
Amazing.
