### ISSUE TITLE
Reduce reactive computations for app.

### ISSUE THREAD

**Issue by medied** [DemocracyEarth/sovereign#260]
App is currently starting up with 1754 computations. Some basic use will take it up to 5000+. 

We should optimize to reduce number of computations. By stopping template subscriptions once data has been gathered and replicating them in memory, the system can stop listening to the server nonstop via ddp and hence reduce reactive computations potentially to < 1000 at startup. This will impact perception in mobile experience.

**Comment by santisiri** [comment]
This was a major refactor, now completed across the board. It will improve speed of app significantly.
