### ISSUE TITLE
Git binary not found in $PATH

### ISSUE THREAD

**Issue by jonathandandries** [DemocracyEarth/sovereign#266]
# This is a (Bug Report / Feature Proposal)

#### :tophat: Description

For bug reports:
* What went wrong?

Cannot bring up the app using docker-compose.

* What did you expect should have happened?

The application would come online.

* What was the config you used?

Nothing.

* What stacktrace or error message from your provider did you see?

The docker-compose solution does not work because you need to have git installed for npm to start. I have a fix that I will submit as a pull request. In the meantime, here are the steps to reproduce:

```
docker-compose build
docker-compose up -d
# ... wait a minute for the containers come up ...
curl localhost:3000
# ^^^ no response
docker-compose logs
```

snip:

```
app_1    | This is your first time using Meteor!
app_1    | Installing a Meteor distribution in your home directory.
app_1    | Downloading Meteor distribution
app_1    | npm ERR! code ENOGIT
app_1    | npm ERR! No git binary found in $PATH
app_1    | npm ERR!
app_1    | npm ERR! Failed using git.
app_1    | npm ERR! Please check if you have git installed and in your PATH.
app_1    |
app_1    | npm ERR! A complete log of this run can be found in:
app_1    | npm ERR!     /home/meteor/.npm/_logs/2018-04-10T20_07_53_153Z-debug.log
app_1    |
app_1    | > Sovereign.app@ start:dev /app
app_1    | > meteor --settings=config/development/settings.json
app_1    |
app_1    | [[[[[ /app ]]]]]
app_1    |
app_1    | => Started proxy.
app_1    | => A patch (Meteor 1.6.1.1) for your current release is available!
app_1    |    Update this project now with 'meteor update --patch'.
```

/snip

#### :clipboard: Additional Data

* ***Sovereign deployment where you found the issue***:

master branch as of 4/10/2018

* ***Browser & version***:

N/A

* ***Screenshot***:

N/A

* ***Error messages***:

See log above.

* ***URL to reproduce the error***:

localhost:3000

**Comment by Cleberw3b** [comment]
Working on PR to fix it
