### ISSUE TITLE
Does Sovereign support Liquid Democracy?

### ISSUE THREAD

**Issue by dhyan40** [DemocracyEarth/sovereign#273]
# This is a (Bug Report / Feature Proposal)

#### :tophat: Description

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

#### :pushpin: Related issues
* #010101

#### :clipboard: Additional Data

* ***Sovereign deployment where you found the issue***:
* ***Browser & version***:
* ***Screenshot***:
* ***Error messages***:
* ***URL to reproduce the error***:

**Comment by dhyan40** [comment]
Democracy 1.0: Direct — One person one vote

Democracy 2.0: Electoral — One person represents the whole district

Democracy 3.0: Liquid — Personalized representation


In a liquid democracy, you always have the option to vote directly, representing yourself.
And you can pick trusted proxies, who can use your extra vote anytime you don't use it yourself.

These are personal representatives: you can pick anyone, and you can replace them immediately anytime.

And if you dont agree with the way your trusted associate voted, you can overrule their vote and vote yourself or authorise another person to vote on your behalf.

Voting power accumulates, creating a fluid network to empower the most trusted people as representatives.

This creates a way to democratically make decisions at scale, with much more inclusion, resistance to corruption, and less polarization into two limiting parties

**Comment by virgile-dev** [comment]
Hi @dhyan40 
We are very much aligned to the definition you outlined above.
Liquid Democracy is already implemented in Sovereign. We still have to add a couple features but the most of it is there. 
Here is how it works : 
![delegation](https://user-images.githubusercontent.com/11473995/38747734-188c87a4-3f4c-11e8-96c9-34bf122bda1d.png)
The modal appears when you over on the user's avatar. You can test it live on vote.democracy.earth

**Comment by virgile-dev** [comment]
I'm closing this. Please don't hesitate to re-open if you have more questions.
