### ISSUE TITLE
MetaMask Login support.

### ISSUE THREAD

**Issue by santisiri** [DemocracyEarth/sovereign#279]
If we can allow signing in by simply allowing people to sign a public address on the Ethereum blockchain by using MetaMask to do that.. then we had solved anonymity in the platform.

Imagine combining that with the cooptation mechanism we are designing: you sign in anonymously yet the system considers you legitimate... this would be huge for communities like Julio Coco's Disidentes in Venezuela.

**Comment by virgile-dev** [comment]
Hey @santisiri 

I'm a bit confused by the second paragraph of this issue. While I think signing with Metamask can offer some degree of anonymity to the user, how do you think people can vote on member approval if members are anonymous. 

Is the person joining the organization supposed to contact users that are already in the organization, share with them their address and ask them to vet it by sending votes to it ?

Aragon's approach of using Keybase to store publicly of privately signed proof that the user is the owner of the address. See this blog post : https://blog.aragon.one/how-aragon-approaches-identity-and-the-ethereum-keybase-resolver-d548133e4a26?source=---------4------------

**Comment by danknobs** [comment]
I love this idea. But please consider the extra complexity added to the user/average Venezuelan that doesn't knows MetaMask or has basic blockchain knowledge. Tutorials would be needed.

**Comment by santisiri** [comment]
@danknobs this is definitely for the advanced user today but it has been requested by venezuelan dissidents that need a certain way to engage in political activism online while preserving their identity. crypto cannot be simplified 100% but we do our best to deliver the simplest ux.

**Comment by medied** [comment]
Basic login now working on branch `279-metamask-login`, PR coming after more testing and some polishing
