### ISSUE TITLE
One vote per person, per issue. 

### ISSUE THREAD

**Issue by paulamlb** [DemocracyEarth/sovereign#283]
Allowing posts to be one vote per person per issue.

**Comment by medied** [comment]
@paulamlb @santisiri is this something that still makes sense? I'm uncertain

**Comment by santisiri** [comment]
I don't view this as critical as securing app on other fronts (debating, better navigation and security).

**Comment by medied** [comment]
Yea was talking to Pau about this and we feel the same way. Will let her comment but I think we can remove this issue by sprint meeting on Monday.

**Comment by santisiri** [comment]
If you think about it... we are actually **already** capturing the signal of one person one vote.. it's just a different way of counting the votes in the system. It's redundant to build feature, eventually we can focus on different ways of tallying winning result.

**Comment by paulamlb** [comment]
> we are actually already capturing the signal of one person one vote 
- Indeed.

- I think this discussion can be postponed to when we are operating with the vote token.... It will be important to give this option for organizations that want to ensure all users have equal power.

**Comment by santisiri** [comment]
I'll assign this to the [Version 1.0.0 milestone](https://github.com/DemocracyEarth/sovereign/milestone/1).

**Comment by dhyan40** [comment]
I also think one vote per issue per person should be the default option -- it is confusing to see the results -- What was the real intention for allowing a person to cast multiple votes per issue -- this gets quite confusion.

**Comment by paulamlb** [comment]
It allows users to prioritize by giving different weights to different issues. Prioritizing is a fundamental need for every organization - possibilities are always limited. Multiple votes enables a clear picture of what is most relevant at any given moment. Nevertheless, with our timestamps any user / org can see exactly how many voters are in favor or against a position and is able to do their accounting based on that if they so prefer.

**Comment by petrk94** [comment]
I agree here with @dhyan40.
I want to use it in a germany regional politics and where people can say yes or no to a proposal. more than just 1 vote would cause much more questions how to use it or how to count it.
Even the german law and acceptance of this legitimation would make problems. Im already so far that the regional politics would count the votes, if I tell them now they have to calculate it other way they would say "no thanks, but this cause to much workload on our site" to me.
For germany we need 1 vote per person per proposal.

**Comment by santisiri** [comment]
[This will be available in the next release](https://github.com/DemocracyEarth/sovereign/commit/929b5e72010a692b83fd27d1201ab8e537692095).
