### ISSUE TITLE
User experience: what does `venezuela.democracy.earth` redirect to?

### ISSUE THREAD

**Issue by medied** [DemocracyEarth/sovereign#287]
The content for the voting questions ~~is being created collectively in this google doc~~ will be posted by each organization directly

**Comment by virgile-dev** [comment]
Hey @paulamlb @medied 

Building on your idea of using specified accounts to propose questions. 
How about we create several accounts: 
- One on which proposals would be candidates. We could put up for proposal official candidates but also civil candidates that might me able to run for elections that we could crowdsource through the community
- One where we would ask more meta questions on the legitimacy of the elections, on programmatic points of policy etc.

The main feed could be used for people to ask question spontaneously and reflect what's on the mind of the users.

What do you guys think ?

**Comment by santisiri** [comment]
I really like these ideas @medied. 

@aecc I think he means we create a `@NicolasMaduro` account and quote him in the platform, and that we do as such with other figures too. Also start with an official account for the state of Venezuela. Replicating the political universe in the platform.

**Comment by aecc** [comment]
aha, that's interesting @santisiri, that would make it seem more real. What would they "write" on their timeline? Would we impersonate them? Or just mention them?

I understood it more like a way to just filter questions. @virgile-dev I like the idea, I would just put both accounts into a single one, first the candidates question, then legitimacy questions. In this way we would increase the probability of people answering all polls instead of one or the other. By the way, does the platform support something else than yes/no answers? If we have to add a candidate list that could need to be developed

**Comment by medied** [comment]
>could you quickly summarize what's the idea behind "using specified accounts" ?

Right, idea being that the questions to be voted on would be 'published' by a specific account (a 'Venezuela' account so to speak). This is different than, for example, what we did with Sri Lanka where the domain `srilanka.democracy.earth` redirects to all posts using a #srilanka hashtag (ie: https://vote.democracy.earth/tag/srilanka). It's a matter of what's the best strategy to use `venezuela.democracy.earth`. 

I like these ideas though. We want to come up with the content of the voting questions collectively, using this [google doc](https://docs.google.com/document/d/1TZcLo_ucrXoIJzc4M7eGQtsDVcDSJ7osLomdpiiCq-U/edit) to start. Whether we end up with two sets of questions, like candidates and meta, that's exactly what we can explore and debate.

**Comment by santisiri** [comment]
> aha, that's interesting @santisiri, that would make it seem more real. What would they "write" on their timeline? Would we impersonate them? Or just mention them?

Do you know how to use DeepFake? :)

> Right, idea being that the questions to be voted on would be 'published' by a specific account (a 'Venezuela' account so to speak). This is different than, for example, what we did with Sri Lanka where the domain srilanka.democracy.earth redirects to all posts using a #srilanka hashtag (ie: https://vote.democracy.earth/tag/srilanka). It's a matter of what's the best strategy to use venezuela.democracy.earth.

We should do this for every Nation-State by the way. I'm thinking that maybe makes more sense for the redirect to point towards a `/peer` rather than a `/tag`, so we would have a user for each country and make those questions official (we'll work towards legitimizing them as we get better with `proof-of-identity`).

**Comment by medied** [comment]
Trying to think about implementation details though. For the 'meta' questions, any one of us can propose before hand, we arrive at a set of questions we want to vote on, then those get shown via `venezuela.democracy.earth`. 

For 'candidate' questions, would we have to define a list of candidates before hand? Or if people want to nominate someone, they add the candidates themselves? That could get somewhat messy. Should we use a specific hashtag for spontaneous nominees? 

>I would just put both accounts into a single one, first the candidates question, then legitimacy questions. In this way we would increase the probability of people answering all polls instead of one or the other.

It's true that if `venezuela.democracy.earth` doesn't point users to a streamlined experience we run the risk of people just being confused. 

Just thinking out loud.

**Comment by virgile-dev** [comment]
@aecc Yeah maybe one account would do the trick. As @santisiri we should use what's there so let's use hashtags to curate content. 

Here is an idea of how we could implement that: 
![venezuela](https://user-images.githubusercontent.com/11473995/38996928-8917e55a-43ec-11e8-8982-51e7537b7bce.png)

**Comment by medied** [comment]
Alright so as the project advances we are understanding what may be the best dynamic for the questions. Sovereign is simply the medium, the space that venezuelans have been deprived of, where any organization or individual can participate and propose ideas. That means there can be Sovereign accounts for different organizations and they can post the questions directly, kinda like in Twitter.

Still not completely nailed yet is where `venezuela.democracy.earth` redirects to, but maybe it can just redirect to `#venezuela` tag. It ocurred to me the other day it would be awesome also to explore the idea of URLs for multiple tags, aka something like:

`https://vote.democracy.earth/tag/venezuela&vlzaresiste&dimision`

**Comment by medied** [comment]
Building off of my last message in this thread, it is almost time to set up redirect for `venezuela.democracy.earth` already. Now that we have the main hashtag `#VzlaProponeCambio` and this whole initiative is solid around it, I'm wondering if it makes sense for `venezuela.democracy.earth` to redirect to it as in:

`https://vote.democracy.earth/tag/vzlaproponecambio`

Thinking about the user experience, and if we really want to drive and spread `#VzlaProponeCambio` everywhere for the initiative to grow, this option could be the easiest because then users just have to include that one hashtag for their voice to be included and heard in the right channel. 

@paulamlb @santisiri what do you think? The other option of course is having the domain redirect to `#venezuela` hashtag. This would mean users would have to include both hashtags maybe (?), feels a bit less structured.

**Comment by paulamlb** [comment]
Can we point to both hashtags?

**Comment by santisiri** [comment]
After chatting with @virgile-dev and @medied in the office we agreed to take the path proposed in #319

**Comment by medied** [comment]
Closing this one as #319 is now closed as well
