### ISSUE TITLE
Re-incorporate the agora feature

### ISSUE THREAD

**Issue by virgile-dev** [DemocracyEarth/sovereign#289]
Hey @santisiri @medied @paulamlb 

Now that proposal have individual pages, should we try to re-incorporate the agora feature to allow people to comment on these ?

Not sure this is relevant milestone to do this, but though it might be worth asking.

**Comment by aecc** [comment]
Actually, on the meeting with the venezuelans we had, some people were requesting to be able to discuss venezuelan matters after/during/before the parallel voting. So it would be a good idea.

**Comment by santisiri** [comment]
We can do threaded replies, it's easier with the structure we have now in the app. An experience similar to twitter exchanges.

**Comment by virgile-dev** [comment]
Alright will add this to our UX to dos :) @AlexJupiter

**Comment by santisiri** [comment]
@virgile-dev yes! key aspects:

- display of replies
- button to reply (same position as composer in original feed? different icon?
- reply button in feed items

**Comment by AlexJupiter** [comment]
@virgile-dev sounds exciting! Might be a while until we get onto it mind you, [we do have a task in the product roadmap for the UX of debates](https://github.com/DemocracyEarth/sovereign/projects/11#card-7774652). Does this link in with the work that Gruff are doing?

**Comment by santisiri** [comment]
Please consider that if we can achieve results with reutilization of components, this will always have a priority than building/designing something from scratch in terms of development.

**Comment by virgile-dev** [comment]
Here is just a first shot at it without threaded replies.
![replies](https://user-images.githubusercontent.com/11473995/38999885-0ec8f972-43f3-11e8-8248-f50b77bc1ead.png)

We should consider adding on the card a counter that signals how much comments a proposal has.

**Comment by santisiri** [comment]
looks good!

**Comment by santisiri** [comment]
I will bring this one back to the May 4 deadline. I think it can be done by then.

**Comment by SFSandra** [comment]
At some point would it be possible or desirable  to enable upvoting/downvoting on comments in the agora? (would that be a re-utilization of the yes/no voting components?)

**Comment by paulamlb** [comment]
AI can use this to track consensus points among groups that disagree...

**Comment by santisiri** [comment]
> Can I include debate feature in our spanish tutorials? In other words, will it be ready before May 15?

My hopes are on yes.

**Comment by santisiri** [comment]
[here we go](https://github.com/DemocracyEarth/sovereign/commit/e2fe34a7f3209fb362f07a70b06c7781f8e64280).

**Comment by santisiri** [comment]
[done](https://github.com/DemocracyEarth/sovereign/commit/23efd8a7d7622f10ffe14f0f2d7269880779fed2).
