### ISSUE TITLE
Tag view is broken in production

### ISSUE THREAD

**Issue by virgile-dev** [DemocracyEarth/sovereign#291]
Hey @santisiri 

I tried displaying a few hashtag on vote.democracy.earth but nothing is displaying
<img width="1279" alt="capture d ecran 2018-04-18 a 18 29 44" src="https://user-images.githubusercontent.com/11473995/38945382-ac70161e-4336-11e8-9e7f-a93d2c752360.png">

**Comment by santisiri** [comment]
I'll check on this. It's a bug I've seen before.

**Comment by santisiri** [comment]
[fixed](https://github.com/DemocracyEarth/sovereign/commit/b89b0cb5202c62737c321459c5c899fcb4ec6dfd)
