### ISSUE TITLE
Good Country pre-election

### ISSUE THREAD

**Issue by paulamlb** [DemocracyEarth/sovereign#306]
Aiming to have a proposal by May 6.

[Good country](https://goodcountry.org/global-vote) wants to map who are the viable candidates for Venezuela's presidential elections. @medied they want to do an independent process, on their own time, and not following the narrative of the regime. 

Here are a couple thoughts for how to format this: 

- Create a goodcountry.democracy.earth jurisdiction pointing to good country's account.

- They create a hashtag (ex: #vzlapreelecciones ) and start asking for suggestions from Venezuelans. Then establish what is the threshold of votes for a candidate to be valid

or 

- They can create users impersonating potential candidates of Venezuela, that post their quotes and then they account for the number of delegations those users get. Other users can suggest more potential candidates to be impersonated.

**Comment by santisiri** [comment]
> They can create users impersonating potential candidates of Venezuela, that post their quotes and then they account for the number of delegations those users get. Other users can suggest more potential candidates to be impersonated.

I like this approach. We can include something in the avatar to signal it's just a representative account (and by include in the avatar.. in the image used as avatar, dont expect code for that).

**Comment by medied** [comment]
I'd lean away from impersonating, I'm not understanding right now how that would play out. Or maybe I'm misunderstanding the idea entirely, maybe 'impersonating' is not the right word in this case. 

Are we talking about getting a read or pulse on what's the support behind certain Venezuelan leaders? That is an idea we had explored earlier, and it makes sense to me for Good Country to execute on that front. From the Sovereign point-of-view, are we talking about gauging the support in the number of delegations (to a fake account) or the votes received (by a candidate proposition by Good Country)? 

Paula and I were talking about that and exploring. It would be key that anyone could 'nominate' a leader. Also we considered timelines, we mentioned this doesn't necessarily have to be done by May 20th, it could be a good action to take post May 20 to keep momentum going. Also I think we all agree we should remain within the flexibility that Sovereign offers.

**Comment by paulamlb** [comment]
> We must definitely follow momentum first.

What does that mean exactly?

If we prepare to launch elections a couple days after the launch of the initiative, this gives us more time to create a collaborative process with some of the other organizations involved in the initiative, where together we can determine how to access who are the potential candidates, and then **more importantly** what exactly will be the criteria to select the official candidates for the good country venezuelan election (top 5 most voted, or everyone that gathers 10% of the total amount of tokens owned by users of venezuela.democracy.earth, etc.) .

+

it is a good thing to keep the momentum going. a couple of days after launching the initiative, make a lot of noise saying "we are starting good country's venezuela's pre-elections! Join now" or something like this. Maybe even with a video from Simon and others describing the initiative.....

What do you think?

If by your comment you meant build momentum in advance of launch that we can try to speed up the process and make it inclusive anyways. Having a say from Venezuelans (that are living in Venezuela) is critical, many times we pivoted completely because of what they had to say.

**Comment by paulamlb** [comment]
So launching on May 20 to cease the moment where the world is paying attention.

I have a proposal:

This is not any election, it's a liquid democracy election. Meaning that we can center this around ideas, **policies** , and create room for the proponents of the best ideas to surface as political leaders. 

We can have discussions around policies by having impersonated accounts from the main potential candidates listing what they have proposed in the past on many different things like economy, health, political reform and education (to be determined). We put an orange layer on top of the photo of the impersonated accounts signaling they are impersonations.  

Each topic has a hashtag like #monetaryregulation (in adittion to the #venezuela hashtag), so that everyone who wants to analyze the different propositions on a given topic can access it. And then we let the delegations begin. The top x with more delegations qualify for the elections. Might be the regular political candidates, or might be people like Ricardo Hausmann, or a young student, or an activist.  

Of course it will involve intense hustling.

**Comment by SFSandra** [comment]
@paulamlb I like that idea.  The representative avatars (which is what you mean by impersonations, right?) w/ orange filter becomes an ideas-based 'representation of the representative', correct? enabling leaders/Leadership to emerge from ideas & be voted on.

**Comment by santisiri** [comment]
@paulamlb no. each paragraph makes a good post. structure the conversation that way.
