### ISSUE TITLE
can't delegate - Wont show the slider for the liquid bar 

### ISSUE THREAD

**Issue by paulamlb** [DemocracyEarth/sovereign#309]
Wont show the slider for the liquid bar 

<img width="307" alt="screen shot 2018-05-03 at 15 07 06" src="https://user-images.githubusercontent.com/18194034/39594665-b99f6a34-4ee3-11e8-8c09-2deeb95f8610.png">

**Comment by santisiri** [comment]
Aware of this. Should be fixed when we include profiles in the feed directly. Will include in milestone.

**Comment by santisiri** [comment]
Seems to happen with specific users. Likely legacy accounts. Will review asap.

**Comment by santisiri** [comment]
[looks like it was indeed a legacy way of handling delegations](https://github.com/DemocracyEarth/sovereign/commit/798fc5fa79f90201aedb2791dd28c76b24a2752c)

Will verify in production since it has older data than in my node.
