### ISSUE TITLE
Delegations stopped working.

### ISSUE THREAD

**Issue by santisiri** [DemocracyEarth/sovereign#310]
Not being properly accounted.

**Comment by santisiri** [comment]
[fixed](https://github.com/DemocracyEarth/sovereign/commit/ac8b586817c2f29c3aa150842ba24a6db445fea8)

**Comment by santisiri** [comment]
@vjrj @virgile-dev it would be interesting to get tests related to delegations.

**Comment by vjrj** [comment]
Sure.

This remains me something simple I read recently:
```
You don't write tests to make sure your code works now: you write tests so that you can spot your code breaking in the future.
```
https://dev.to/ptrbrynt/my-testing-epiphany-4en2
