### ISSUE TITLE
Some of the /tag endpoints failed to render

### ISSUE THREAD

**Issue by medied** [DemocracyEarth/sovereign#325]
Take this one for example:

https://vote.democracy.earth/vote/estao-curtindo-o-nibs-2018-ilheus-nibs2018-q506#debate

From left to right, the first tag renders fine and the second redirects to a `Looks like that page does not exist` page. 

First one is pointing to this:

<img width="354" alt="screen shot 2018-05-14 at 3 14 53 pm" src="https://user-images.githubusercontent.com/4752599/40018335-f6d1af44-5789-11e8-9ac4-da3832fd5d74.png">

Second one adds the '#' which seems to be breaking it:

<img width="420" alt="screen shot 2018-05-14 at 3 15 02 pm" src="https://user-images.githubusercontent.com/4752599/40018351-0123a7e0-578a-11e8-9a6b-e0497fce01b0.png">

Could that be the issue?

**Comment by santisiri** [comment]
Yes, this is a known bug. I'll work on it asap.

**Comment by santisiri** [comment]
[fixed and in deploy right now](https://github.com/DemocracyEarth/sovereign/commit/5cfe8e91667ed41585acd52840b9eb3e26999e86)
