### ISSUE TITLE
Replies in debates are sometimes logged as generic arguments.

### ISSUE THREAD

**Issue by Hydrogenn** [DemocracyEarth/sovereign#332]
When writing a reply, or anything in a debate, it has sometimes moved itself to the front, and not marked as a reply of any kind.

This happened while I was creating multiple tabs to look at issues that interested me in more detail, so recreating this might involve:

- Typing text in the argument
- Leaving the tab
- Joining back in and finishing the argument

**Comment by santisiri** [comment]
Yes, I realized this during the weekend checking your comments. Thanks for reporting. Will fix asap.

**Comment by santisiri** [comment]
[This should not happen anymore](https://github.com/DemocracyEarth/sovereign/commit/a4eacc5f433de13029263311f5e1a324106a6233)
