### ISSUE TITLE
typo in email recovery "you" in yellow box should be "your"

### ISSUE THREAD

**Issue by herbstephens** [DemocracyEarth/sovereign#337]
![image](https://user-images.githubusercontent.com/11063638/40377480-e30bd8a0-5da5-11e8-8ad5-15808a30ca08.png)

# This is a (Bug Report / Feature Proposal)

#### :tophat: Description

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

#### :pushpin: Related issues
* #010101

#### :clipboard: Additional Data

* ***Sovereign deployment where you found the issue***:
* ***Browser & version***:
* ***Screenshot***:
* ***Error messages***:
* ***URL to reproduce the error***:

**Comment by santisiri** [comment]
fixed.
