### ISSUE TITLE
Wrong link on "See result" button in the email notification

### ISSUE THREAD

**Issue by virgile-dev** [DemocracyEarth/sovereign#338]
The link takes me to the peer's profile. I was expecting it would take me to the proposal's page.
<img width="550" alt="capture d ecran 2018-05-23 a 10 49 47" src="https://user-images.githubusercontent.com/11473995/40413828-1ac2aaea-5e77-11e8-8974-76a37573b52d.png">

**Comment by santisiri** [comment]
[fixed](https://github.com/DemocracyEarth/sovereign/commit/548de59382590e5ab882a8ece8eeed1c1b023c33)
