### ISSUE TITLE
On mobile proposals and comment section don't have the same width as the width

### ISSUE THREAD

**Issue by virgile-dev** [DemocracyEarth/sovereign#342]
This causes a weird UX when scrolling down as it move to the left and to the right.
![capture d ecran - 2018-05-30 a 17 29 10](https://user-images.githubusercontent.com/11473995/40730635-6a27030c-642f-11e8-90c6-28ad19f4ffe7.png)

**Comment by santisiri** [comment]
Fixed in the last deploy today.
