### ISSUE TITLE
Sovereign not working on Firefox Desktop v60.0.1

### ISSUE THREAD

**Issue by virgile-dev** [DemocracyEarth/sovereign#345]
When trying to load the page I get
`Oops, looks like there's no route on the client or the server for url: "https://vote.democracy.earth/."` 

It works on chrome.

**Comment by santisiri** [comment]
Damn.. can you send a screenshot or something more detailed? Will download ffox, haven't used it in a while.

**Comment by virgile-dev** [comment]
Looks like it's the analytics package that's messing it up.
<img width="1279" alt="capture d ecran 2018-06-06 a 17 27 22" src="https://user-images.githubusercontent.com/11473995/41048664-86c7d33a-69af-11e8-8875-ff21de4a9647.png">

**Comment by virgile-dev** [comment]
Hey @santisiri 
Inspecting the code it looks like it's crashing because the google script is not between <head></head>
Could be that's what causing this bug. 

<img width="409" alt="capture d ecran 2018-06-07 a 17 36 01" src="https://user-images.githubusercontent.com/11473995/41110381-80441b7a-6a79-11e8-95e6-f2e8bffa8fc8.png">

**Comment by santisiri** [comment]
There's no google script.. just a package that is used by the app that does these things. This nonetheless should not be a reason for this happening at all.
