### ISSUE TITLE
[Thread] Allow for upvoting/downvoting of comments

### ISSUE THREAD

**Issue by santisiri** [DemocracyEarth/sovereign#35]
Comment system still has pending to integrate upvoting with Transaction engine.

**Comment by medied** [comment]
Here are two examples of similar thread comments voting:

Reddit:
![reddit-voting](http://giphy.com/gifs/VEoIcqIOvQlQ4)

Hacker News:
![hn-voting](http://giphy.com/gifs/Z7zDvpQBUP1lu)

I'm starting to implement something more Reddit-like, which (from the current code) seems to be what @santisiri intended in the first place. Will keep everyone posted.

**Comment by bhack** [comment]
I don't know if voting can really scale or unbiased at scale? What about https://conversationai.github.io ?

**Comment by bhack** [comment]
See also https://github.com/conversationai/perspectiveapi/issues/2

**Comment by virgile-dev** [comment]
For the time being the `agora` component has been scaled out to focus on core features. Hence closing

**Comment by virgile-dev** [comment]
Go checkout #projectgruff in our Slack. It's a project being lead by a member of the community to enable productive debate on a web interface.

**Comment by kajmagnus** [comment]
@virgile-dev Ok I had a look in Slack.

@medied, about: *"I'm starting to implement something more Reddit-like"* — Just curious about if you made any progress? and how did the user interface / design / UX you had in mind look? ... I've been working with something similar to HN and Reddit comments and votes, in case you'd like to have a look?

**Comment by medied** [comment]
@kajmagnus noup, that comment was a while back and this issue became outdated. Although we might be resurfacing the agora component again, maybe a more updated issue thread would be a better place to talk
