### ISSUE TITLE
Auth0 support

### ISSUE THREAD

**Issue by leog** [DemocracyEarth/sovereign#353]
# This is a Feature Proposal

#### :tophat: Description
[Auth0](https://auth0.com) is a very renowned authentication service which provides full access control over users. It provides very different ways to enable authentication, OAuth2, etc.
It would be great to have documentation around how a new authentication method could be added to Sovereign, or better yet, implement into Sovereign a fairly open standard authentication to hook up services such as Auth0.

#### :bulb: Backstory
We want to use Sovereign to provide a transparent way to vote within a new initiative called [MiVoz](https://mivoz.uy) (MyVoice in english) only available in Uruguay for now which relies on Auth0, more information [here](https://auth0.com/blog/nonprofit-mivoz-hopes-to-upgrade-democracy-with-auth0/). MiVoz provides a platform where people can debate ideas, improve them collaboratively to then vote for them. The passed voted ideas can then be used by any entity freely, like traditional existing political parties. Those ideas will **for sure** be part of a new Uruguayan political party based on ICT called [Partido Digital](https://partidodigital.org.uy) (Digital Party in english), which committed to adopt them as part of their governance plan for starters.

**Comment by santisiri** [comment]
Happy to help in any possible way on this integration. Is there any library that can be used to integrate Auth0 on Meteor projects?

**Comment by leog** [comment]
Thanks @santisiri. I think [meteor-auth0](https://github.com/xcv58/meteor-auth0) would be the best option now.

**Comment by leog** [comment]
Any news @santisiri?

**Comment by santisiri** [comment]
Hi @leog we are glad to help but we don't have resources of democracy earth to develop this thing specifically for you. If you want to implement and do a pull request we can review.

**Comment by santisiri** [comment]
> Thanks @santisiri. I think meteor-auth0 would be the best option now.

Did you install this package? it looks pretty straightforward.

**Comment by santisiri** [comment]
identity / signup / login code can be found here: https://github.com/DemocracyEarth/sovereign/tree/master/imports/ui/templates/components/identity/login

**Comment by leog** [comment]
Thanks @santisiri for the info.
Is there any way you can maybe prioritize adding SAML authentication? That should tackle a broader audience than adding Auth0 and we can still leverage it for our purposes.

**Comment by santisiri** [comment]
Looking for some references for this to understand it better. (ie: https://stackoverflow.com/questions/40213195/meteor-accounts-obtaining-the-saml-response-token-user-after-log-in). Looks something that we can include in the scope of our current work.

Pinging @medied since he manages `identity` on Sovereign.

**Comment by medied** [comment]
I understand this was completed [via Freelancer](https://www.freelancer.com/projects/javascript/OAuth-integration-with-Meteor-App/), closing for now but feel free to reopen if needed.
