### ISSUE TITLE
Update profile page

### ISSUE THREAD

**Issue by medied** [DemocracyEarth/sovereign#358]
Show token number/stakes

**Comment by santisiri** [comment]
We'll need design for this, @AlexJupiter

**Comment by AlexJupiter** [comment]
@santisir I will post a sketch soon to share vision and align, then I can create a mock-up.

**Comment by virgile-dev** [comment]
Hey @santisiri @medied @AlexJupiter 
Here's a first stab at this.
![profile-modal-crypto](https://user-images.githubusercontent.com/11473995/43211006-d86b86ee-9030-11e8-93c4-c2535c40cf0d.png)

**Comment by medied** [comment]
> The link on anonymous anonymous0x883e2 goes to the profile page.

Not a bad idea. 

Thanks for taking a first stab at this Vir, curious to see how simplified it can end up for MVP with only one token per address.

**Comment by AlexJupiter** [comment]
@virgile-dev thanks for taking this on (and apologies for being AWOL at the moment everyone). 

Do you have a Figma link? 

A couple of pointers:
- Not a huge fan of having scrolling in a pop-out, do we anticipate the need for scrolling here? How many tokens are realistically going to be attached to one address?
- K = thousands, and M = millions right? Having two (or more) different units could get very confusing. You don't think we could have everything in thousands? 
- "Last fetch" is super critical 👍 , however just wondering if we could make that more human readable, say "Today at 5:05PM BST" or "Yesterday at 11:00AM PST"

**Comment by santisiri** [comment]
Amazing step @virgile-dev, really like it.

Good observations @AlexJupiter. Definitely a more human readable `lastFetch` works, but key data point for sync.. Maybe directly signal "Synced" in green if we can check against Web3. Scrolls in popups only work well under `input` boxes as a suggest for search. In this case we can list directly in profile somehow.. and maybe paginating if > 5 tokens? Not sure.

@medied I think from a UX perspective we should figure out a multi-token approach.. that said, the pattern should render well in the case of one token per account.

**Comment by virgile-dev** [comment]
Hey @AlexJupiter 
Just invited to the Figma I was working on.
Couple of thoughts based on your comments:
- Agree on a more human readable `last fetch`, wondering if it should be down to the minute or a the second. **How often are we going to fetch balances ?** @LucasIsasmendi
- I'm uncertain about the % of supply metric. In most cases it's going to be 0.000x something, if we kep it defining the number of decimals there is gonna be crucial.
- On total number of tokens, it's tricky to go only by thousands, hundreds or whatever. 1 BTC is a lot, 5000 MANA isn't. I think we need this adaptative approach that goes from the unit and scales to the million. 
- About the scrolling in a pop-out, I used the `input` class layout to create my table layout. 
- Agree with @santisiri we should be working on a design that works with one token and several. @medied keep in mind that to one ETH address can be attached several ERC20s (at least that's how I'm thinking about it).

**Comment by virgile-dev** [comment]
Hey guys, 
Just had a call with @AlexJupiter on how to handle the design process. We find that using issues like this works pretty well.

We are going to create 3 more issues based on the core user journeys:
- Create a proposal available for certain holders of a said token
- Find a proposals related to a token
- Vote on a proposal with a percentage of your stake
- Delegate a percentage of your stake to another user

We'll be posting sketches there and raising questions to figure out the UX of the crypto governance mvp.

**Comment by medied** [comment]
Sounds good. I'm currently working on making the user wallet an array (see #370), which is a step towards updating the profile UI to display multiple tokens

**Comment by virgile-dev** [comment]
Hey @AlexJupiter I like your changes.
The manual sync is a good idea but first we should understand what those updates mean for the whole app. We have an issue for this https://github.com/DemocracyEarth/sovereign/issues/371.

**Comment by santisiri** [comment]
hi @AlexJupiter, this looks great..

Regarding the token icon, check the examples I'm attaching here. We'll go with this style everywhere to signal a token in the same way we signal a flag of a given country.

Really liked the idea of the sync button.

<img width="831" alt="screen shot 2018-08-14 at 2 57 01 pm" src="https://user-images.githubusercontent.com/2153166/44112154-58b8e552-9fd2-11e8-8f9a-8c353ae71a6c.png">
<img width="825" alt="screen shot 2018-08-14 at 2 56 56 pm" src="https://user-images.githubusercontent.com/2153166/44112155-58c2f466-9fd2-11e8-8dd9-22491a683cd2.png">
<img width="290" alt="screen shot 2018-08-14 at 2 56 49 pm" src="https://user-images.githubusercontent.com/2153166/44112156-58d75730-9fd2-11e8-9663-93b7e1a1a632.png">

**Comment by virgile-dev** [comment]
Here is an updated version @santisiri with a couple specs detailed and questions to address. 
<img width="771" alt="capture d ecran 2018-08-16 a 07 33 00" src="https://user-images.githubusercontent.com/11473995/44190357-ae4e5b00-a126-11e8-8885-77e2f1594dab.png">

**Comment by santisiri** [comment]
The blockchain address should be present below the Name and Nationality, in a small letter format (similar to the one used for dates in `feedItem`). I don't think we should use multiple address as signature of an account. 

Yes all token icons should be clickable and send you to a `/token/feed`. 

We should use something a bit more graphical.. a small bar, to express the quantity of tokens and cast amount... not so excel like.  A green bar with little height.. I remember seeing some @AlexJupiter along those lines.

**Comment by santisiri** [comment]
voilá.

<img width="316" alt="screen shot 2018-08-20 at 10 57 10 pm" src="https://user-images.githubusercontent.com/2153166/44377844-7c454c00-a4cc-11e8-850e-20558a47b320.png">

**Comment by santisiri** [comment]
<img width="275" alt="screen shot 2018-08-22 at 6 57 23 pm" src="https://user-images.githubusercontent.com/2153166/44495243-3c51a680-a63d-11e8-84df-0db410d4b9a5.png">

Also thought of a way of showing total supply share.. with a tiny cake icon that slices in 4.. if you have all 4, you own 100% of supply. if it only shows 1 slice, means < 25% of supply... simple icon with a tooltip.. probably quantities should not be literally quarters.

**Comment by virgile-dev** [comment]
Love your implementation @santisiri !
