### ISSUE TITLE
Discuss login options

### ISSUE THREAD

**Issue by medied** [DemocracyEarth/sovereign#365]
Need for many login options or only Metamask? Minimize confusion?

**Comment by santisiri** [comment]
Can we get stats of Toshi vs. Metamask? Any other platforms we should consider. Hunch says let's keep going with Metamask as we speak since we have already started that integration (minimize course of change in ongoing effort).

**Comment by santisiri** [comment]
Issue #357 refers to this.

**Comment by medied** [comment]
Agree we can continue with Metamask, will complete #356 as soon as possible. 

In reality this issue came up regarding email and Facebook login options, and whether those current options would cause confusion with Metamask (as proof of stake democracy would not work directly with email/Facebook)

**Comment by santisiri** [comment]
i think we should allow multiple options as we plan an `exodus` from facebook to freedom.

**Comment by medied** [comment]
Switching non-code-specific issues to Basecamp
