### ISSUE TITLE
Discuss when the user needs to login

### ISSUE THREAD

**Issue by medied** [DemocracyEarth/sovereign#367]

**Comment by santisiri** [comment]
To vote he must certainly sign that.

**Comment by medied** [comment]
Right, currently Sovereign allows a user to see ballots without being logged in. She's required to log in only once she wants to interact (vote/delegate) with a ballot. If this behavior is appropriate for this milestone then this may be all we need.

Leaving this open for now as there are other UX flow questions that still need to be nailed down (#371 for example)

**Comment by santisiri** [comment]
Yep.. rule of thumb: free speech always, to interact simply proof of stake (or web2 shit).

**Comment by medied** [comment]
Switching non-code-specific issues to Basecamp
