### ISSUE TITLE
Research tasks

### ISSUE THREAD

**Issue by medied** [DemocracyEarth/sovereign#368]
- [ ] Projects and content for ballots
- [ ] Diffusion method, Telegram, message language/instructions
- [ ] Sovereign accounts for different projects?

**Comment by SFSandra** [comment]
Hey @medied by diffusion method do you mean, how we'll promote the ballots/accounts?

**Comment by medied** [comment]
@SFSandra yea exactly, how we get the promote or share the right ballots to the appropriate people

**Comment by medied** [comment]
Switching non-code-specific issues to Basecamp
