### ISSUE TITLE
Establish basic UX flow to handle balance update

### ISSUE THREAD

**Issue by medied** [DemocracyEarth/sovereign#371]
Idea is to address the question of what happens when there's a mismatch between the balance in the user's wallet and the balance being read from Metamask

**Comment by santisiri** [comment]
- `blockchain address` related to avatar should alway be accessible. 
- one balance per token?

**Comment by santisiri** [comment]
sorry accidentally closed.

**Comment by medied** [comment]
The overall consensus among the team is that users should have the ultimate say on where their tokens remain staked after an balance update. That is, when there is balance update/mismatch/change between what is recorded in our DB and what the `publicAddress` possesses at the moment, the app can do some updating automatically, show pending status where appropriate, and ultimately let user decide and confirm. More specifically, this will possibly require some changes regarding:
- UI updates to indicate pending status
- Sync/connection with daemon as appropriate (#361)
- What is learned from user journeys (#379) and other user research and test, it's ongoing learning

These should be translated into specific issues as needed.
