### ISSUE TITLE
Can't customize username after Metamask signup. 

### ISSUE THREAD

**Issue by santisiri** [DemocracyEarth/sovereign#374]
After Metamask signup, I wanted to modify the default given username and it did not allow for that change. 

I can only login with the automatically generated username. This shouldn't be that way. I should be able to link my Ethereum address with a custom username in the platform. 

<img width="319" alt="screenshot 2018-07-16 18 10 33" src="https://user-images.githubusercontent.com/2153166/42770134-8d54041e-8924-11e8-9588-ca30bcddd660.png">

**Comment by medied** [comment]
Was able to find a bug in the logic that to update username, it turns out updating the username was buggy for any user (regular email signup, Metamask, etc). Proposing fix in PR #376
