### ISSUE TITLE
User journeys for Crypto Opensource Governance 

### ISSUE THREAD

**Issue by virgile-dev** [DemocracyEarth/sovereign#379]
Hey guys,

I'm working on the user journeys for the new COG release.
I created a branch called [test-scenarios](https://github.com/DemocracyEarth/sovereign/tree/test-scenarios/) and will be working with the [test framework](https://github.com/DemocracyEarth/sovereign/tree/test-scenarios/features) that @vjrj set up for us so the work done for the user journeys can be implemented into tests later on. 

I'll be posting higher level stuff on the issue to document progress and get answers from the rest of the team. @AlexJupiter you are welcome to contribute!

**Comment by virgile-dev** [comment]
## User journey from the POV of COG feature
- [ ] Registering and login
  - [ ] With Metamask
    - [ ] Fetch ERC20 balances
    - [ ] Display tokens I have a stake in on my profile
    > At this stage I'm wondering if we should just use this balance to validate if the user has the right to vote on token related topics (constituency). **I'm using this hypotesis for now as its way easier to operate.**

  - [ ] Receiving $VOTEs upon account creation
  > The user registering with Metamask is still a normal user, so it should get its $VOTEs allocation either way.

  - [ ] Edit account information
  > When the user logs in with Metamask we don't get its email. In the edit profile modal we should the email field. If we want to keep the confirm your email loop we can send a new email every time it's changed.

  - [ ] Logout

- [ ] Exposing proposals
  - [ ] Expose proposals linked to $ticker (/token)
  > We should be thinking of how the user finds proposals related to the tokens he has stakes in. There are a few ways we could tackle this:
  - Tokens I have a stake in are displayed on my profile page, clicking on the token could take the user to a feed displaying proposal only availbale to vote for this token holder.
  - Use the $ticker (/token) filtering option available on Sovereign and use it as an input to define who is authorized to vote. If there are 2 $tickers in one proposal we could assume that both constituencies can vote ? Could be nice to allow comma seperated values for the consituency fields restricting the voters' unviverse.
  - Display in the $ticker feed all proposal that inputed a token name in the constituency modal.

- [ ] Authoring
    - [ ] Proposal with constituency (wip)
      - [ ] Fill Token holders field
      >
      - To avoid confusion we should only accept tickers. Would be nice to diplay a list of possible values that is reactive to what the user tipes in (like the nationality field, we could even have the token logos)
      - Allow for comma seperated values

    - [ ] Proposal with $ticker
    > When drafting a proposal and including a $ticker, the constituency option gets activated and the field token holder get filled with the $ticker value.

- [ ] Voting and revoking
    - [ ] Allocate n votes on proposal
    > When a user tries to allocate $VOTE on a $ticker related proposal Sovereign verifies that this token is listed in the user's profile and that it's most updated balance in that token is > 0. If conditions are not met show error message "You cannot vote on this proposal because you are not a token holder".

    - [ ] Withdraw n votes on proposal
- [ ] Delegating
    - [ ] Send n votes to another user
    - [ ] Remove n votes given to delegate
    - [ ] Show delegates on sidebar menu

**Comment by AlexJupiter** [comment]
@virgile-dev do you want to collaborate sometime to put this user journey into some sketches. [Like we did for the DAPP?](https://projects.invisionapp.com/freehand/document/HrEjYEBv4)

**Comment by virgile-dev** [comment]
Hey @AlexJupiter

In short here are the 4 user journeys we'll be working with (I'm linking the issues related that have already been created) : 

- Sign up and see token balance https://github.com/DemocracyEarth/sovereign/issues/358
- Update balance https://github.com/DemocracyEarth/sovereign/issues/371
- Create a proposal available for certain holders of a said token https://github.com/DemocracyEarth/sovereign/issues/388
- Find a proposals related to a token https://github.com/DemocracyEarth/sovereign/issues/362
- Vote on a proposal with a percentage of your stake https://github.com/DemocracyEarth/sovereign/issues/363
- Delegate a percentage of your stake to another user

Let's collaborate on the Figma to provide the devs with some sketches and the insights related to it.

**Comment by virgile-dev** [comment]
# Sign up and see token balance
<img width="730" alt="capture d ecran 2018-08-16 a 08 01 57" src="https://user-images.githubusercontent.com/11473995/44191249-b7412b80-a12a-11e8-85c3-ce57b56a60f7.png">

**Issues to address**
- How to deal with non ETH addresses ? (Signup process, display of addresses on profile, several blockchain addresses on the same account or seperate account. @LucasIsasmendi may help with his work on IOV)
- Nailing proper decimals display will need iterations to be nailed 
- Need to define the mechanics behind fetching the balances (automatically by the daemon and manually every time the user logs in or clicks the sync button)
- We should @AlexJupiter concern of the use of modals to display so much info. Maybe we should circle back to the designs we did with Agniezska for the profile page https://github.com/DemocracyEarth/sovereign/issues/278

**Comment by medied** [comment]
Guys doing some cleanup now post v1.0.0-beta, closing this for now
