### ISSUE TITLE
Error message cannot reach any url on vote.democracy.earth via Chrome Windows or Firefox

### ISSUE THREAD

**Issue by SFSandra** [DemocracyEarth/sovereign#384]
# This is a Bug Report 

#### :tophat: 

For bug reports:
* What went wrong?"I basically can't reach any url on vote.democracy.earth. I'm facing this error when trying to reach the voting app, from a notification email : Oops, looks like there's no route on the client or the server for url: "https://vote.democracy.earth/vote/data-protection-and-lack-of-transparency-due-to-the-digital-divide-or-illectronism-illiteracy-in-tech-mg5y." 
* What did you expect should have happened? this issue is submitted on behalf of a community member who sent this notification in by email to hello@democracy.earth (Jonathan Piron)
* What was the config you used? The link seems to work on Chrome for Android, but not on Chrome for Windows, neither on Firefox (desktop or mobile). 
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

#### :pushpin: Related issues
* #010101

#### :clipboard: Additional Data

* ***Sovereign deployment where you found the issue***:
* ***Browser & version***:
* ***Screenshot***: 
![image](https://user-images.githubusercontent.com/24529258/43369812-17faafce-9329-11e8-8c4c-ff0c7cbf065f.png)

* ***Error messages***: Oops, looks like there's no route on the client or the server for url: "https://vote.democracy.earth/vote/data-protection-and-lack-of-transparency-due-to-the-digital-divide-or-illectronism-illiteracy-in-tech-mg5y." 
* ***URL to reproduce the error***: Many thanks in advance, and a big thumbs up for the work you're accomplishing!

**Comment by santisiri** [comment]
It's working now. Probably a server thing back then.
