### ISSUE TITLE
Some suggestions about optimaizing vote.democracy.earth/

### ISSUE THREAD

**Issue by jasonlt250** [DemocracyEarth/sovereign#385]
1.There could be a hyperlink from the homepage www.democracy.earth to vote.democracy.earth.
2.The proposals could be ranked by the most voted ones on the top because those are usually people's most concerned.
3.The process of voting should be anonymous in order to protect voters' privacy.

**Comment by santisiri** [comment]
Ranks are definitely happening.

Also we'll be hosting on democracy.earth domain once app is ready to be out of alpha.

Anonymity in voting is addressed in our paper, in the time being we rather have the software not lie about how votes get stored in premises.
