### ISSUE TITLE
Missing header/logo-navbar

### ISSUE THREAD

**Issue by billytunin** [DemocracyEarth/sovereign#390]
This ain't really a bug. Probably just something I'm missing.

So I'm on "master" branch, just playing around and testing the app. I followed the installation guide and everything's cool. I also ran the seeds for the database, so I do have a populated db with the Colombian demo database. The only problem I've found is that the header is not rendering at the top. Meaning I can't log-in, nor sign-up a new user. What am I missing?
Screenshot:
<img width="1440" alt="screen shot 2018-08-15 at 19 20 39" src="https://user-images.githubusercontent.com/15022688/44176661-15d1bf80-a0c1-11e8-9247-35a7d56d5b60.png">

**Comment by santisiri** [comment]
Yeah, we are undergoing a major redesign, which we expect to finish within the next couple of weeks. 

Header was removed from the system and we're relocating login info as we speak. Our release date is expected for August 31 and due to the scope of this change, we are changing code in `master`.

**Comment by billytunin** [comment]
Aahh, I see. Alright, no prob. We can close this one out then.
