### ISSUE TITLE
trying to register new user and it says it's already registered

### ISSUE THREAD

**Issue by paulamlb** [DemocracyEarth/sovereign#395]
<img width="293" alt="screen shot 2018-08-27 at 19 45 20" src="https://user-images.githubusercontent.com/18194034/44692643-d8125680-aa31-11e8-8772-8add3ba79e2b.png">

**Comment by paulamlb** [comment]
it started working, then started saying "User not found" when I tried to log in. Now this again:

<img width="307" alt="screen shot 2018-08-28 at 17 44 02" src="https://user-images.githubusercontent.com/18194034/44752794-1e2af100-aaea-11e8-942b-98b9671e4b66.png">

**Comment by santisiri** [comment]
has this been fixed already with the new deploy @medied @paulamlb ?

**Comment by paulamlb** [comment]
yes! you can close

**Comment by paulamlb** [comment]
@medied what was the error that started to happen last night, after this one? I forgot to add it here, but it had something to do with me registering a new user and then not being able to login, maybe it said something like user not found. Do you remember @medied ? We just waited some minutes and then it stopped happening.

**Comment by medied** [comment]
Can't remember exactly either, the behavior we were seeing was probably related to connection between app and server after deploy. I'd say it's safe to close this one out, open a new one if issue reappears.
