### ISSUE TITLE
guidelines for contributing

### ISSUE THREAD

**Issue by LucasIsasmendi** [DemocracyEarth/sovereign#40]
when create a new issue, the link goes to the Contributors list, it should go to best practices, style guide,  norms and other standards.
Something like this: https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md

**Comment by santisiri** [comment]
You fixed, that right? Now seems to be working like that.

**Comment by LucasIsasmendi** [comment]
Nop, we need to write down the contributing guide, that is different to the contributors list. 
Open a new issue, then click the link "Please review the guidelines for contributing to this repository."
