### ISSUE TITLE
email addresses needed for DEF updated TOS/Privacy Policy

### ISSUE THREAD

**Issue by SFSandra** [DemocracyEarth/sovereign#405]
# This is a Feature Request

#### :tophat: Description

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
Jason Hanania has updated the DEF TOS/privacy policy to be compliant with GDPR [(here)](https://3.basecamp.com/3506967/buckets/2755999/todos/1249079210).  **The following 5 emails have are within the text of the TOS / privacy policy and need to be created.** These can point to one two or three  of the following: hello@/santi@/sandra@ 

- admin@
- agent@
- violations@
- appeal@
- gdpr@

* If there is additional config how would it look

#### :pushpin: Related issues
* #010101

#### :clipboard: Additional Data

* ***Sovereign deployment where you found the issue***:
* ***Browser & version***:
* ***Screenshot***:
* ***Error messages***:
* ***URL to reproduce the error***:

**Comment by SFSandra** [comment]
These email addresses are part of the Terms that Jason finalized. Once the terms are publicized (which I'm assuming will be soon), certain emails referenced in the text of the Terms must be operational.  

admin@
agent@
violations@
appeal@
gdpr@

**Comment by BarnabyThing** [comment]
Do I need to respond to this Sandra?

**Comment by SFSandra** [comment]
Hi Barnaby, nope, not sure why you're on this thread - t's just some items related to the foundation's Terms of Service policy.
