### ISSUE TITLE
revocation 

### ISSUE THREAD

**Issue by paulamlb** [DemocracyEarth/sovereign#407]
don't know if that's intentional, but it seems like the button on the right should say something like "Remove votes" or "Revoke" instead of "Vote" when people are removing their votes from a ballot.

<img width="394" alt="screen shot 2018-09-19 at 16 43 51" src="https://user-images.githubusercontent.com/18194034/45780389-7a85ba00-bc2b-11e8-8788-688afdac42d1.png">

**Comment by medied** [comment]
closing as pre-release issue
