### ISSUE TITLE
Call for testers

### ISSUE THREAD

**Issue by dialex** [DemocracyEarth/sovereign#41]
I'm not a Javascript developer but I'm a tester.

- Is it helpful that testers explore the app and report issues here on GitHub?
- Is it helpful to create automated E2E tests at the UI level (Selenium Driver)?

**Comment by LucasIsasmendi** [comment]
Yes, both are helpful, if you check our to do list you will see the test area and the pending tasks (write unit and integration tests and connect with circleCI).
