### ISSUE TITLE
login improvement 

### ISSUE THREAD

**Issue by paulamlb** [DemocracyEarth/sovereign#413]
Have the button be "MetaMask"

And the linked text underneath it be "Set up your Metamask" 

Just so people understand that both are connected...

<img width="313" alt="screen shot 2018-11-13 at 12 31 28" src="https://user-images.githubusercontent.com/18194034/48432110-72388f80-e741-11e8-9cba-2c7e07eb8fc1.png">

@santisiri

**Comment by santisiri** [comment]
We include a video now.
