### ISSUE TITLE
unable to cast votes at testnet.democracy.earth

### ISSUE THREAD

**Issue by SFSandra** [DemocracyEarth/sovereign#415]
# This is a Bug Report 

#### :tophat: Description

For bug reports:
* What went wrong? when I click "Vote" on a proposal on testnet.democracy.earth, screen locks up
* What did you expect should have happened? I expected to click "vote" and MetaMask to open and ask me to confirm sending VOTE tokens to the delegatee/proposal
* What was the config you used? Desktop, Chrome browser on a MacBook Air
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

#### :pushpin: Related issues
* #010101

#### :clipboard: Additional Data

* ***Sovereign deployment where you found the issue***:
* ***Browser & version***:
* ***Screenshot***:
* ***Error messages***:
* ***URL to reproduce the error***:
![image](https://user-images.githubusercontent.com/24529258/48633757-cc6f6580-e978-11e8-8f7e-194bf73c8b12.png)

**Comment by medied** [comment]
Was able to replicate: `votePrice` does not always get set on contract creation. Any contract without `votePrice` set will:

-  fail to retrieve`Template.currentData().contract.blockchain.votePrice,` in ballot.js
- and therefore will hang in `const quantityWithDecimals = addDecimal(quantity.toNumber(), 18);` in metamask.js as `quantity` gets passed in as undefined. 

I have added a [band-aid patch](https://github.com/DemocracyEarth/sovereign/commit/d4d6bef068afd166468f5a7feec751a5f652c8bd) to handle an undefined `quantity` until we get to the bottom of this, so it should work in the meantime

**Comment by medied** [comment]
Unable to replicate again, seems to have got fixed in the polishing following those days though couldn't pinpoint exactly where. @santisiri will leave the `(quantity === undefined)` handling just in case, closing for now
