### ISSUE TITLE
Unable to login at votest.democracy.earth using Brave browser

### ISSUE THREAD

**Issue by ConorOkus** [DemocracyEarth/sovereign#416]
I'm not able to login using metamask on the test network using the Brave browser.

I get the following error in the developer console.

<img width="837" alt="screenshot 2018-11-16 at 20 36 09" src="https://user-images.githubusercontent.com/10757874/48646189-0b84d180-e9e0-11e8-83ab-7ffa0fb5530d.png">

**Comment by medied** [comment]
Hey @ConorOkus thanks for reporting. Could you replicate and confirm:
- Metamask version you are using
- Brave version
- do you have Metamask's [privacy mode](https://medium.com/metamask/introducing-privacy-mode-42549d4870fa) enabled?
- does the error come up when you are connected to any network? Or is it in Rinkeby or a specific one

**Comment by medied** [comment]
I see, can you try upgrading Metamask to the latest version?

**Comment by juanguren** [comment]
> There didn't seem to be an obvious way to upgrade Metamask in the Brave browser.
> 
> I had to uninstall then reinstall Brave and download Metamask from the Chrome web store (feels weird).
> 
> Then sign into Metamask using my seed phrase, but use the older version not the beta. The newer beta version didn't recognise my seed phrase.
> 
> So currently:
> 
> Metamask Version - 5.0.2
> Brave Version - 0.56.12
> 
> I'm now able to login to votest.democracy.earth

Hey @ConorOkus 

I´m having the same issue using Brave browser and would like to ask you: How did you saved your tabs before reinstalling? (If you had any)

**Comment by ConorOkus** [comment]
Hi @juanguren 

I didn't actually have any bookmarks as I've only been using Brave for a short time. Most of mine are still on Chrome. 

Chrome allows you to export your bookmarks via the bookmarks manager I'm not sure if the previous version of Brave has that option but that would be your best bet. 

That would give you a .html file that you can save somewhere and then import it when you install the new version of Brave.

Hope that helps pal.

**Comment by medied** [comment]
@ConorOkus glad you were able to login after Metamask update, closing this for now but please feel free to open a new issue if something else comes up 👍

**Comment by juanguren** [comment]
Hey @ConorOkus, there´s an option to recover tabs after restarting computer but with "reinstalling brave" has been hard to find. Will ask on Brave community. Thanks!
