### ISSUE TITLE
Profile does not meet voter requisites error

### ISSUE THREAD

**Issue by paulamlb** [DemocracyEarth/sovereign#417]
Got "Your profile does not meet voter requisites".

<img width="444" alt="screen shot 2018-11-16 at 16 55 50" src="https://user-images.githubusercontent.com/18194034/48649450-a2da2c80-e9c0-11e8-9a79-e538fe1eea11.png">

But I had just created that post with another account and didn't add any voter requisites. 

Also, I had VOTE in the account the I was using to vote, so that wasn't it.  

This was the post:

https://votest.democracy.earth/2018/11/16/we-should-vote-every-day-pcfm

**Comment by medied** [comment]
Seeing the same behavior from others (#419), the cause of this issue seems to be cache mismatch between Metamask and Sovereign, part of more fine-tuning that's needed

**Comment by medied** [comment]
Issue is that `voteEnabled` was getting set only `onCreated` for the ballot templates, so with a new user login (without a page refresh) the conditionals for `_cryptoVote` would end up in the wrong place. Refreshing `voteEnabled` at the beginning of `_cryptoVote` ensures it works as expected even when there is a new user login.
