### ISSUE TITLE
Upgrade Login options - can't log with e-mail

### ISSUE THREAD

**Issue by nelruk** [DemocracyEarth/sovereign#418]
### What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
For old users such as myself who always log with my e-mail, now I don't have the option to do it. It only appears the Metamask option, not more other.

###  If there is additional config how would it look
Work with the fussion for old users of metamask account and old account to not lose the progress.
![imagen](https://user-images.githubusercontent.com/5068576/48668245-84ab2400-eac7-11e8-85ed-684c02466374.png)

**Comment by medied** [comment]
Hey @nelruk good to see you here. Yeap: this new release represents a big make over from previous version, including the email login being removed as of right now. Definitely want to work with old users like yourself! We are actually still going through the transition, as we are now rolling out beta version at testnet.democracy.earth first (I see the image shows vote.democracy.earth). We did a clean database reset of the instance at testnet.democracy.earth (currently redirects to _votest_ in the meantime). Do you have Metamask installed?
