### ISSUE TITLE
Can't cast vote: Unable to find the required tokens in your wallet

### ISSUE THREAD

**Issue by xuhcc** [DemocracyEarth/sovereign#419]
# This is a Bug Report

#### :tophat: Description

When I'm trying to cast a vote, the modal window appears with the message "Unable to find the required tokens in your wallet".

![1](https://user-images.githubusercontent.com/1660460/48671745-faea6d80-eb3d-11e8-917e-fdd3600ed837.png)

In browser console:

```
VOTE
checking for WEI
NOT HAS TOKEN
```

(tokens are actually on my address)

#### :clipboard: Additional Data

* ***Sovereign deployment where you found the issue***: https://votest.democracy.earth/
* ***Browser & version***: Firefox 63.0.1 Metamask 5.0.2

**Comment by xuhcc** [comment]
I solved this by manually removing these items from local storage:

```
Meteor.loginToken
Meteor.loginTokenExpires
Meteor.userId
```

**Comment by medied** [comment]
@xuhcc thanks for reporting this issue and glad you resolved, this is part of more fine-tuning that will be coming in the next few weeks. Will close this issue for now but please feel free to reopen if it persists
