### ISSUE TITLE
[Question] Are there features planned for community editing (and version control) of proposals?

### ISSUE THREAD

**Issue by josiahsprague** [DemocracyEarth/sovereign#42]
Apologies if this isn't the right place to ask a question. I just got the app up and running. It's super exciting to finally get a chance to contribute to the work you all are doing. :) 

While clicking around the app, I'm not seeing any features for editing a proposal either by the original user or other users. Is this a feature that's planned? Is there a roadmap or conversation for features like this? I don't see anything related to this in the [projects tab](https://github.com/DemocracyEarth/sovereign/projects).

**Comment by LucasIsasmendi** [comment]
We have pending issues in the `milestone:v0.1.0 ` related with editing. 
Also we have several features to develop and some others to integrate. Currently working heavily in the app structure to reflect meteor standards (check my fork for further details) and to implement testing.
If you have more questions, ideas, proposals, or want to chat with us, we are [on gitter](https://gitter.im/DemocracyEarth/sovereign?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).
