### ISSUE TITLE
Limit to debate levels/children 

### ISSUE THREAD

**Issue by jetlej** [DemocracyEarth/sovereign#43]
Once you get down past 6 or 7, the width of the form/comment gets extremely thin and unusable depending on screen size. 

I'd suggest adding a limit, or stopping the indentation at a certain level.

**Comment by santisiri** [comment]
Good suggestion. Is there any clear reference for example on how Reddit or Hacker News impose limits to threading?

**Comment by jetlej** [comment]
I don't believe they have restrictions. I just looked at both, and what's different is that they are both full-screen and the indentation is smaller, or becomes smaller on mobile screen widths.

**Comment by domi41** [comment]
An alternative would be to allow the debating section to go full-page, and visually hide replies in the condensed mode.

**Comment by virgile-dev** [comment]
For the time being the `agora` component has been scaled out to focus on core features. Hence closing
Go checkout #projectgruff in our Slack. It's a project being lead by a member of the community to enable productive debate on a web interface.
