### ISSUE TITLE
custom token address doesn't work on firefox

### ISSUE THREAD

**Issue by paulamlb** [DemocracyEarth/sovereign#431]
two screenshots were taken one after the other... custom token address works on chrome but not on firefox 

<img width="421" alt="screen shot 2018-11-28 at 21 02 50" src="https://user-images.githubusercontent.com/18194034/49194439-2d237880-f351-11e8-88ce-f035e96294df.png">
<img width="368" alt="screen shot 2018-11-28 at 21 03 32" src="https://user-images.githubusercontent.com/18194034/49194438-2d237880-f351-11e8-9b1f-a3c0e359d0c5.png">

**Comment by medied** [comment]
Was able to add token with my setup

**Comment by medied** [comment]
We were able to get the token info to appear on Firefox, likely a network mismatch
