### ISSUE TITLE
No political Affiliation, perspective from newcomer / feedback.

### ISSUE THREAD

**Issue by rvalle** [DemocracyEarth/sovereign#433]
Just came across this project. Looks very interesting.

at first I felt a bit uncomfortable by the mockup of Putin and hacking elections in Readme.md, I dont think it belongs in a project like this.

I also think it is incompatible with the "no political affiliation" statement below.

**Comment by nelruk** [comment]
They refer "political affiliation" as they don't have support or look support from political parties (political parties organizations, i.e. Democratic Party or GOP).

**Comment by santisiri** [comment]
The Putin commentary is a cheek-in-tone joke. I don't think anyone takes that seriously. We had one with Julian Assange last year. Keeps changing.
