### ISSUE TITLE
cannot share Sovereign posts to Twitter using Tweet share button

### ISSUE THREAD

**Issue by SFSandra** [DemocracyEarth/sovereign#438]
# This is a Bug Report 

#### :tophat: Description

For bug reports:
* What went wrong? When I click the share to Twitter button, nothing happens
* What did you expect should have happened? a Twitter api window should open, with the Sovereign post embedded in a ready-to-send Tweet
* What was the config you used? Google Chrome, also Brave browser. Same problem in both browswers.
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

#### :pushpin: Related issues
* #010101

#### :clipboard: Additional Data

* ***Sovereign deployment where you found the issue***:
* ***Browser & version***:Chrome Version 71.0.3578.80 and Brave Version 0.56.15 Chromium:
* ***Screenshot***: ![not working](https://user-images.githubusercontent.com/24529258/50057452-89431680-011f-11e9-80f0-7cdb12ccef05.png)

* ***Error messages***: this page isn't working

* ***URL to reproduce the error***: https://twitter.com/share?url=https%3A//votest.democracy.earth/2018/12/14/original-survey-by-coindesk-st-gme8&text=Original%20survey%20by%20@coindesk%20%27state%20of%20blockchains%20%22The%20dominant%20political%20ideology%20of%20crypto%20is%20liberal%20at%2031%,%20but%20conservatives%2018%,%20libertarians%2019%,%20and%20ancaps%207%%20make%20a%20total%20of%2044%%20that%20can%20be%20...

**Comment by santisiri** [comment]
We fixed this, urls now have a cap length.
