### ISSUE TITLE
No navigation button on top left

### ISSUE THREAD

**Issue by bodnandi** [DemocracyEarth/sovereign#439]
# This is a (Bug Report / Feature Proposal)

#### :tophat: Description

For bug reports:
* What went wrong?
Nothing. There are no 'New', 'Etherum', 'Earth' and 'Democracy earth' buttons I can click on to navigate.

Hope you can see screenshot image below.

* What did you expect should have happened?
N/A

* What was the config you used?

Windows 7, Firefox Quantum 64.0 (64 bit)
* What stacktrace or error message from your provider did you see?
N/A

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

#### :pushpin: Related issues
* #010101

#### :clipboard: Additional Data

* ***Sovereign deployment where you found the issue***:
* ***Browser & version***:
* ***Screenshot***:

![image](https://user-images.githubusercontent.com/45951389/50115058-3613b580-023e-11e9-9eb8-38a80cfdde00.png)

* ***Error messages***:
* ***URL to reproduce the error***:

**Comment by santisiri** [comment]
can you give us a screenshot of your profile card? clicking on the top left. you should at least see the `Now` button in the latest release live on testnet now.

**Comment by bodnandi** [comment]
Sorry for the late reply. Thought I included a screenshot in the query.Firefox:



Chrome:



    On Friday, 21 December 2018, 20:05:59 GMT, Santiago Siri <notifications@github.com> wrote:  
 
 
can you give us a screenshot of your profile card? clicking on the top left. you should at least see the Now button in the latest release live on testnet now.

**Comment by medied** [comment]
This issue seems to be related to #443. @bodnandi I pushed a commit to address it, can you confirm the expected sidebar buttons are back? Feel free to close this issue if so. And thanks for flagging it in the first place!

**Comment by bodnandi** [comment]
Sorry, but now joy still!



    On Tuesday, 22 January 2019, 20:44:30 GMT, Eduardo Medina <notifications@github.com> wrote:  
 
 
This issue seems to be related to #443. @bodnandi I pushed a commit to address it, can you confirm the expected sidebar buttons are back? Feel free to close this issue if so. And thanks for flagging it in the first place!

**Comment by nandorbodo** [comment]
Why did you guy close this? There is still no navigation buttons on the horison:

![image](https://user-images.githubusercontent.com/47043720/51866496-011c7780-2341-11e9-9e9c-679cc58a011a.png)

**Comment by medied** [comment]
Hey @nandorbodo, from that screenshot you need to click the top-left button

**Comment by bodnandi** [comment]
Thanks it works now!
But the interface changed now a bit. Its cool.
    On Thursday, 31 January 2019, 19:02:04 GMT, Eduardo Medina <notifications@github.com> wrote:  
 
 
Hey @nandorbodo, from that screenshot you need to click the top-left button
