### ISSUE TITLE
Ballot section is unclear

### ISSUE THREAD

**Issue by jetlej** [DemocracyEarth/sovereign#44]
What exactly is that slider for? Do I have 100 potential votes to give to any one proposal? Some initial instructions or a tooltip would be great :)

**Comment by santisiri** [comment]
As we are working with the notion of liquid democracy, in this current implementation, users get 100 tokens to either vote on topics or delegate to other users. This will be more clear when we implement the configuration wizard for setting up an Institution (and its rules) on a Sovereign node.

**Comment by domi41** [comment]
The ballot flow has changed significantly. Please re-open this if the confusion persists.
