### ISSUE TITLE
Votes not registering on site despite successful transaction, confirmation window will not complete, lock up until complete

### ISSUE THREAD

**Issue by votedave** [DemocracyEarth/sovereign#441]
![10vote_1](https://user-images.githubusercontent.com/17741338/50617914-80797f80-0f2a-11e9-96e2-7c75ebd7fa41.JPG)
![10vote_2](https://user-images.githubusercontent.com/17741338/50617916-81aaac80-0f2a-11e9-981c-38049d6238ab.JPG)
![no vote showing now](https://user-images.githubusercontent.com/17741338/50617917-82dbd980-0f2a-11e9-8944-7bc2dbf79817.JPG)
![screen hang](https://user-images.githubusercontent.com/17741338/50617920-840d0680-0f2a-11e9-833e-bbe7f7954c4a.JPG)

# This is a (Bug Report / Feature Proposal)

#### :tophat: Description

For bug reports:
* What went wrong?
I have attempted to delegate 10 votes, transaction is successful via Rinkeby BUT the confirmation window in app continues to show progress but never completes, locking out page completely.  Only solution is page refresh.

* What did you expect should have happened?
I expected to see votes attributed to user and post, neither occurs, user confirms receipt of tokens 

* What was the config you used?
Win 10 Pro Build 17134.472
Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)

* What stacktrace or error message from your provider did you see?
No error messages visible or received

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

#### :pushpin: Related issues
* #010101

#### :clipboard: Additional Data

* ***Sovereign deployment where you found the issue***:
* ***Browser & version***:
* ***Screenshot***:
* ***Error messages***:
* ***URL to reproduce the error***:

**Comment by medied** [comment]
Closing for now but please feel free to let us know if issue persists on your end
