### ISSUE TITLE
Some users cannot see Now button

### ISSUE THREAD

**Issue by SFSandra** [DemocracyEarth/sovereign#443]
# This is a Bug Report
#### :tophat: Description

For bug reports:
* What went wrong? Several community members reporting they do not see the Now link in their navigation panel. 
* What did you expect should have happened? Users are expecting to see a "home" or "Most recent' navigation button. 
* What was the config you used? There are multiple reports by multiple users, using Chrome and Firefox browswers
* What stacktrace or error message from your provider did you see?  They simply do not see the 4 nav items above the Delegates section in the nav side panel on the left.

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.  ""Navigation is not easily understood or achieved - How do you get to current threads?""
* If there is additional config how would it look.  All users would see the Now button visible in their navigation panel above the Delegates section

#### :pushpin: Related issues
* #010101

#### :clipboard: Additional Data

* ***Sovereign deployment where you found the issue***:
* ***Browser & version***:
* ***Screenshot***:
* ***Error messages***:
* ***URL to reproduce the error***: https://votest.democracy.earth/2019/1/13/hi-sandra-what-is-this-now-bu-svmf

**Comment by votedave** [comment]
No Now Button with 
Version 71.0.3578.98 (Official Build) (64-bit)
Chrome 
![now button and other nav](https://user-images.githubusercontent.com/17741338/51230766-281b9680-199c-11e9-815a-82fe7ced8bcb.JPG)
Console Snip from Windows 10pro 64

**Comment by SFSandra** [comment]
Two more community  members reporting no Now button visible.

**Comment by SFSandra** [comment]
![another now](https://user-images.githubusercontent.com/24529258/51430898-410f8c00-1bd6-11e9-8e20-f74c02db600c.png)

**Comment by medied** [comment]
Thank you @SFSandra for flagging this issue. I've pushed a commit to address it, can you confirm the 'Now' button is back? Feel free to close this issue if so

**Comment by SFSandra** [comment]
I've always been able to see it! But posted this Issue for 3 users who could not, and they all verify they can now see the buttons that they could not see (Now, DemocracyEarth and user jurisdiction) so will close, thx @medied
