### ISSUE TITLE
Unable to cast vote on Sovereign testnet

### ISSUE THREAD

**Issue by SFSandra** [DemocracyEarth/sovereign#455]
# This is a Bug Report

#### :tophat: Description

For bug reports:
* What went wrong? When I cast a vote, MetaMask sends a message that transaction is complete, but the votes are not showing up where I am staking them, the process gets arrested, I just see a spinning 'wait' icon. I am able to make a post no problem, just cannot vote.
* What did you expect should have happened? votes I cast in my MetaMask wallet to show up staked on the proposal that I staked them on.
* What was the config you used? I tried to vote from both Chrome and Brave. I restarted the browsers and the app, and my MacBook Air.
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

#### :pushpin: Related issues
* #010101

#### :clipboard: Additional Data

* ***Sovereign deployment where you found the issue***: https://votest.democracy.earth/
* ***Browser & version***:  Chrome Version 72.0.3626.109,  Brave Version 0.59.34 Chromium: 72.0.3626.81 (Official Build) (64-bit). On my 
* ***Screenshot***:
![image](https://user-images.githubusercontent.com/24529258/53372153-013f7100-3907-11e9-83a1-c29cdafeda29.png)
* ***Error messages***:
* ***URL to reproduce the error***: https://votest.democracy.earth/

**Comment by SFSandra** [comment]
per conversation on Signal!

**Comment by medied** [comment]
@SFSandra this should be fixed now, seems it was an issue with Infura:

https://github.com/ethereum/web3.js/issues/1679#issuecomment-413234902

Can you confirm from your end and close this issue if so?

**Comment by medied** [comment]
@santisiri we should think about what can we do to have Sovereign handle a `null` from getTransaction` more gracefully
