### ISSUE TITLE
Unable to sign in to the mainnet with blockstack ID

### ISSUE THREAD

**Issue by SFSandra** [DemocracyEarth/sovereign#463]
# This is a Bug Report 

#### :tophat: Description

For bug reports:
* What went wrong? received an error message when I tried to log on to Sovereign with Blockstack ID
* What did you expect should have happened? Expected to be redirected to my already-created blockstack ID
* What was the config you used? Chrome Version 72.0.3626.121 (Official Build) (64-bit) on MacBook Air

* What stacktrace or error message from your provider did you see?
![image](https://user-images.githubusercontent.com/24529258/54575652-2a0cd080-49b2-11e9-9d85-730803f65573.png)

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

#### :pushpin: Related issues
* #010101

#### :clipboard: Additional Data

* ***Sovereign deployment where you found the issue***:
* ***Browser & version***:
* ***Screenshot***:
* ***Error messages***:
* ***URL to reproduce the error***:

**Comment by medied** [comment]
Thanks @SFSandra, just updated a configuration that fixes this issue 👍
