### ISSUE TITLE
set-up of sovereign on Ubuntu - not working system crash

### ISSUE THREAD

**Issue by votedave** [DemocracyEarth/sovereign#464]
# This is a (Bug Report / Feature Proposal)

#### :tophat: Description

For bug reports:
* System crashes
* After following instructions listed on site I hoped to open an instance of sovereign hosted locally via my browser
* What was the config you used? Ubuntu 18.04.2 LTS Intel Core i5-4200M, Gnome 3.28.2, OS 64bit - all sovereign config as per instructions
* What stacktrace or error message from your provider did you see? screenshot attached

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

#### :pshpin: Related issues
* #010101

#### :clipboard: Additional Data

* ***Sovereign deployment where you found the issue***:
* ***Browser & version***:
* ***Screenshot***:
* ***Error messages***:
* ***URL to reproduce the error***:
![Screenshot from 2019-03-26 12-01-59](https://user-images.githubusercontent.com/17741338/54971004-78782b80-4fbf-11e9-8c7a-9735efbb6e0d.png)

**Comment by votedave** [comment]
Can I just say that while I'm reasonably IT confident this has not been an easy process and that if the hope is to "replicate" then the process has some way to go.  It would be GREAT to resolve reasonably quickly as I'm trying to set-up a local node for local council business ASAP.
Help and advice appreciated.
Thanks!

**Comment by medied** [comment]
Hey @votedave, did you do the `npm install` before `meteor npm run start:dev`?

>After following instructions listed on site

Can you send me the link to which instructions you are referring to?

**Comment by votedave** [comment]
Hi, yes, followed instructions to the T - I'm NOT a linux user so I'm in foreign territory and do not understand the syntax or language.
I will look at trying to do an install on a Windows Server environment, I'm a little more familiar with that.
Linux version still crashing - any suggestions of how to remove and start again please and if you could, an instruction sheet on How to Install Sovereign and ALL it's components on a virgin install of Linux, in the right order...?
Thanks

**Comment by votedave** [comment]
Instructions are the ones on the Github site - Sovereign repository.

**Comment by azban** [comment]
@votedave i had to use `meteor npm install`. i'm guessing there may be an issue with an existing nodejs version installed that is not what is expected.
