### ISSUE TITLE
Incorrect CORS for agora.decentraland.org (website is not working)

### ISSUE THREAD

**Issue by uniconstructor** [DemocracyEarth/sovereign#478]
# This is a Bug Report

#### :tophat: Description

* What went wrong: main page of agora.decentraland.org didn't load
* What did you expect should have happened: site operates normally
* What stacktrace or error message from your provider did you see?
```
Access to XMLHttpRequest at 'https://api.agora.decentraland.org/translations/en' from origin 'https://agora.decentraland.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

#### :clipboard: Additional Data

* ***Sovereign deployment where you found the issue***: https://agora.decentraland.org
* ***Browser & version***: Brave 0.69.135, based on Chromium: 77.0.3865.120
* ***URL to reproduce the error***: https://agora.decentraland.org

**Comment by santisiri** [comment]
Hi, is the `ROOT_URL` of the app configured for that domain? Also make sure you have the certificates properly configured.

**Comment by uniconstructor** [comment]
@santisiri Tested just now, everything is OK, closing issue.
