### ISSUE TITLE
Unable to sign-up and recover login

### ISSUE THREAD

**Issue by fgnievinski** [DemocracyEarth/sovereign#486]
When I try to login to https://democracy.earth/ it says "User not found." (I've registered a few years ago).  Then when I try to register again, it says "This user is already registered."  The login username is "fgnievinski".  Thanks for looking into this.

**Comment by santisiri** [comment]
We removed this functionality as we are launching a 100% decentralized application in Q1 2020. you can test on https://moloch.democracy.earth
