### ISSUE TITLE
Why in the supported browsers table are present only closed source browsers?

### ISSUE THREAD

**Issue by erotavlas85** [DemocracyEarth/sovereign#49]
Hi,
I really appreciate this project and your effort to create an open democracyOS. However, I noticed a contradictory fact: in the supported browsers table are present only closed source browsers. The only two open source browser firefox and chromium are not considered. This is a very very strange.

**Comment by tadhgpearson** [comment]
Dunno - it's working fine for me in Firefox!

**Comment by brylie** [comment]
Same here. Lets add Firefox to the supported browsers list.

**Comment by erotavlas85** [comment]
Perfect. Thank you

**Comment by brylie** [comment]
PR open (#104).
