### ISSUE TITLE
Accept delegations of vote not working

### ISSUE THREAD

**Issue by virgile-dev** [DemocracyEarth/sovereign#50]
Browser : Chrome : Version 54.0.2840.98 (64-bit)
Testing : local deploy on production settings
Problem : I've been trying several times to create delegations between 2 users I create myself but as I click on accept delegations, it doesn't work. As I check the votes available to me, my vote count hasn't change either.
Screen capture video : file name "accept delegation not working" https://virgiledeville.cozycloud.cc/public/files/folders/824b99e06bd03a9470d6078a4357d8d5

**Comment by santisiri** [comment]
I'll be working on the Transaction engine very soon, it's very buggy still since we had to work fast for the Colombia referendum. Significant improvements should be felt soon, I'll keep you posted on this thread.

**Comment by virgile-dev** [comment]
Delegations don't work that way anymore hence closing.
