### ISSUE TITLE
Cannot load Colombia's Digital Referendum data base on local instance

### ISSUE THREAD

**Issue by virgile-dev** [DemocracyEarth/sovereign#51]
I've been trying to load the Colombia's Digital Referendum Data base on my local instance following this tutorial but couldn't do it : https://github.com/DemocracyEarth/sovereign/tree/master/docs/seed-db

I feel I'm doing wrong when restarting the application.

Could anyone try to do it?

**Comment by LucasIsasmendi** [comment]
There was a missed step in the tutorial, check now. 
You should change 2 settings fields. If you don't have the settings files in your local copy, `git pull` to get them. 
Let me know if works to close the issue

**Comment by virgile-dev** [comment]
Thanks a lot @LucasIsasmendi ! It finally works
