### ISSUE TITLE
A few Questions

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [DemocracyEarth/sovereign#514]
I am pretty sure you have no issues like that opened yet.

# This is a (Bug Report/ And a question)

#### :tophat: Description

For bug reports:
* What went wrong? see the link I provided, to a page WHere I detailed every single problematic aspect.
* What did you expect should have happened? see the link I provided, to a page Where I detailed every single exptectations aspect.
* What was the config you used? also fully mentioned in ccc
* What stacktrace or error message from your provider did you see? Are you talking about the Ethereum Service Provider ?

For feature proposals:
* That this software provides actual sovereignty, as it claims to, to its users, starting with ginving them a way to provision a full, privately owned, and functional Ethereum Blockchain.  Or that you strip out of the project a technology that makes its users dependent on non open source, proprietary service.
* There are proprietary, SAAS Kubernetes, yet everyone in this world can build from source and provision, a fully private, operational Kubernetes Cluster. Blockchain is not more complex than Kubernetes. So no excuse there.

#### :pushpin: Related issues
* none

#### :clipboard: Additional Data

* The link mentioned above : https://github.com/pokusio/le-defi/blob/master/the-broken-list/democracy-earth/README.md

Et bon courage.

**Comment by santisiri** [comment]
We changed our servers to deploy the dapp in our main domain during the time you were playing with our software. You can check the whole thing on [democracy.earth](http://democracy.earth)

The /blockchain project was simply an exploration as a side project we did many years ago, you should realize that.

If you think Ethereum is not real open source, I can't help you with the nonsense. Regarding your french feelings, c'est la vie.

**Comment by Jean-Baptiste-Lasselle** [comment]
> core

* Well, sovereignty starts with own the software you use , especially when this software is acountable for the main feature of a platfrom : voting. So, Would you state in your public vieos, taht the best way for Argentina, to be sovereign, is to vote using an Ethereum Service operated by Jan-Baptiste Lassellle in France ? I would rather say Argentinian people, you must own the machines that operates your votes.
* So that why your software is far from bringing sovereignty, on the contrary, it makes people dependent on https://infura.io , and you are the best person to tell them, in a beautiful video like you did before, who is infura.io, and who owns this company, the servers, and why the argentinian should use those server's to vote, instead of a private `Ethereum` that would legally be their property : so that if someones hacks it, they can complain to justice, just like for a robbery.
* I just dared you to show me how to deploy a prtivate Ethereum Blockchain, if you don't feel like answering this challenge, c'est la vie. I stated, in the repo I mentioned, that as of today, II am a pretty serious professional I believe, or a thief, considering my wage, and have never seen anyone in my life spawn up a privat Etheruem Blockchain, fully functional.

Picking up De Gaulle to make a joke I believe, was the worst idea you could have. Ask the americans.

**Comment by Jean-Baptiste-Lasselle** [comment]
ps: Ouh, and about your https://democracy.earth/ : 
* I tested while I wrote my paper on your organization on github, as I reported im my paper, it is down (hey click on it, it just does nt do anything, just "laoding dependencies" message forever)
*and it's actually the same result today...
* oh it's outdated, so what's the purpose of the 3 days ago [Mobile app release](https://github.com/DemocracyEarth/sovereign/releases/tag/0.8.1) ...? I mean, you should wirte in the release notes "Hey guys, this a brand new mobile release, that is completely outdated, go test it on your phone, don't wait!"

nyway, I will stop this conversation here, I think all my points were clearly made, and you are perfectly free not to answer any. I just believe in making to the public clear, different opinions between professionals, they have both and they make their decisions.
