### ISSUE TITLE
Deploy to heroku button / easy online deployment method

### ISSUE THREAD

**Issue by virgile-dev** [DemocracyEarth/sovereign#52]
It would be really helpful to have a package version of Sovereign to allow easy and fast deployment method. 

At least if someone could set it up on a server it would be great. 

Seems like https://github.com/kadirahq/meteor-up would be a good option

**Comment by LucasIsasmendi** [comment]
Heroku button added to Roadmap input: https://github.com/DemocracyEarth/sovereign/projects/7
Before easy deployment, we should have a friendly launcher feature to setup the instance.
We will vote this when we get our own instance (coming soon)
