### ISSUE TITLE
[popup] if a click happens outside popup, it should deactivate it.

### ISSUE THREAD

**Issue by santisiri** [DemocracyEarth/sovereign#58]
UX improvement: Popup (when clicked on top-right cornet) should disappera if a click happens outside of it.

**Comment by medied** [comment]
Assuming you're talking about the one below, will look at this issue today

<img width="353" alt="screen shot 2016-12-02 at 9 58 33 am" src="https://cloud.githubusercontent.com/assets/4752599/20845175/a1a70354-b878-11e6-9f0e-b9286c8ab548.png">
