### ISSUE TITLE
If no ballot is allocated to a proposal it is not possible to choose a closing date for proposal.

### ISSUE THREAD

**Issue by virgile-dev** [DemocracyEarth/sovereign#59]
And per default its closing date of poll is allocated 24 hours later after topic creation.
<img width="1439" alt="capture d ecran 2016-11-21 a 18 27 07" src="https://cloud.githubusercontent.com/assets/11473995/20493289/752dbb0a-b018-11e6-8f81-dad6bf59a2c4.png">

**Comment by santisiri** [comment]
Oh, you are right. Mmmh.. yes, proposals without ballot shouldn't be timed, makes no sense. Tnx for noticing this one Vir.

**Comment by virgile-dev** [comment]
Also, It'd be great to be able to define the hour of DateClosing because other wise we can't make quick decisions. What do you think?

**Comment by virgile-dev** [comment]
No longer relevant since the `always on` refactor
