### ISSUE TITLE
Request: basic documentation on voting

### ISSUE THREAD

**Issue by PeterDavidCarter** [DemocracyEarth/sovereign#60]
Forgive me if this question is out of turn, but supposing I want to vote for free speech, arts funding, better literature, capitalism with a significant social safety net, less SJWs on campuses, and more investigative policing, but open, not so much covert -- how would I do it? At the moment the project looks potentially impressive but I don't understand it. 

Also, can I do an open collective for my webgame? I'm worried if I make everything open source it'll get hacked to ribbons like the last couple of times, and that I'll end up poor because everyone will steal my code. Is that something you guys care about?

**Comment by santisiri** [comment]
I'm not sure if I properly understand your questions, but we are still working towards a stable first release (v0.1.0) and our goal is to let small/large organizations implement a liquid democracy governance model. Any of those issues could easily be posted inside an instance of an organization running Sovereign. Security-wise we're aiming to let the app operate with a blockchain (hence we're pursuing integrations with 21 & Bcoin) to make sure identities and assigned tokens get stored under an incorruptible ledger.

Regarding Open Collective, I think you'd be better suited to ask them directly -> https://github.com/OpenCollective

**Comment by domi41** [comment]
The [paper](https://github.com/DemocracyEarth/paper) has been published. Read it for further informations.
