### ISSUE TITLE
Participation feed is not showing nothing even though I commented on several proposals.

### ISSUE THREAD

**Issue by virgile-dev** [DemocracyEarth/sovereign#61]
Bug live : https://sovereign.opensourcepolitics.eu/feed?stage=live&kind=vote&peer=Virgile
<img width="1432" alt="capture d ecran 2016-11-22 a 08 30 27" src="https://cloud.githubusercontent.com/assets/11473995/20514745/07196594-b08e-11e6-95da-26633033294f.png">

**Comment by LucasIsasmendi** [comment]
Participation only shows the signed proposals, we should add a new feature to see comments and votes

**Comment by virgile-dev** [comment]
This has been removed. The participation field for user can be displayed by clicking on the user name.
