### ISSUE TITLE
Remove references to Meteor.userId() from Contracts schema 

### ISSUE THREAD

**Issue by utanapishtim** [DemocracyEarth/sovereign#62]
In /imports/api/contracts/Contracts.js there are multiple references to Meteor.userId() that are undefined or null when running server side unit tests. These calls need to be placed in the /imports/api/contracts/methods.js file or replaced with passed parameters, e.g. the calls to Meteor.userId() in Contracts.allow().

**Comment by santisiri** [comment]
PR accepted, tested and seems to be working fine. Makes sense. We should apply this also to other collections (Transactions, Tags, etc).

**Comment by utanapishtim** [comment]
Agreed, should we close this issue?

**Comment by LucasIsasmendi** [comment]
Yes
