### ISSUE TITLE
upvote/downvote on comentaries not working

### ISSUE THREAD

**Issue by virgile-dev** [DemocracyEarth/sovereign#67]
Bug located on [live deploy](https://sovereign.opensourcepolitics.eu/) and local deploy with last version of the code.

<img width="314" alt="capture d ecran 2016-11-23 a 19 42 19" src="https://cloud.githubusercontent.com/assets/11473995/20574556/5128ac1c-b1b5-11e6-9020-b11e186d8e80.png">

**Comment by vicnicius** [comment]
This is a duplicate of https://github.com/DemocracyEarth/sovereign/issues/35

**Comment by LucasIsasmendi** [comment]
Good catch @vicnicius, Thanks!
Check with @santisiri, he is doing some work regarding upvote/downvote. We need to implement some logic to add ID when user u/d to avoid duplication and do OR exclusive (is up OR is down, user can't do both)
