### ISSUE TITLE
"Vote this proposal" button is displaced

### ISSUE THREAD

**Issue by mairwilliams** [DemocracyEarth/sovereign#69]
I'm using Safari version 9.0.2 and seeing this: 

![screen shot 2016-11-23 at 7 55 09 pm](https://cloud.githubusercontent.com/assets/7072387/20574883/0b6a58fe-b1b7-11e6-9f96-c8213d9cf7fd.png)

the icon that goes with "show this proposal" and the words appear one above the other and I guess they shouldn't.

**Comment by domi41** [comment]
Anyone with Safari that can reproduce this bug ?
