### ISSUE TITLE
multiple choice ballot not showing results

### ISSUE THREAD

**Issue by virgile-dev** [DemocracyEarth/sovereign#75]
Visible at  https://sovereign.opensourcepolitics.eu/vote/decide-on-a-controversial-topic-for-medialab-prados-experiment

This feature seems, which is really cool, looks like a work in progress. 

Lots of question raised : how votes are splitted between proposals. For example in the case below what happens if I allocate 5 votes and choose 2 options.

<img width="354" alt="capture d ecran 2016-11-25 a 18 31 10" src="https://cloud.githubusercontent.com/assets/11473995/20632384/5f2bb870-b33d-11e6-8618-6c9c3c169693.png">

**Comment by thatsVishal** [comment]
Is this issue solved yet?

**Comment by virgile-dev** [comment]
Hey @thatsVishal , 

To my understanding, this functionnality hasn't been properly finished. So it's early to go on issue solving on this one.
In term of issue you can lookup to give us hand go check :
- https://github.com/DemocracyEarth/sovereign/issues/187
- https://github.com/DemocracyEarth/sovereign/issues/193
- https://github.com/DemocracyEarth/sovereign/issues/195
- https://github.com/DemocracyEarth/sovereign/issues/197
- https://github.com/DemocracyEarth/sovereign/issues/59 (not sure if resolved yet)

**Comment by virgile-dev** [comment]
Not relevant anymore with refactoring
