### ISSUE TITLE
country selection in profile edition not displaying options

### ISSUE THREAD

**Issue by virgile-dev** [DemocracyEarth/sovereign#76]
@LucasIsasmendi had a look at it it seems that resources don't show because we use https and path are all http. 

visible at https://sovereign.opensourcepolitics.eu/
<img width="294" alt="capture d ecran 2016-11-25 a 19 04 49" src="https://cloud.githubusercontent.com/assets/11473995/20633077/e6de5ad4-b342-11e6-93c1-5dfb2f77e6c2.png">

**Comment by LucasIsasmendi** [comment]
@virgile-dev check mup.js file, the env.ROOT_URL points to 'http://', it should be 'https'

**Comment by vjrj** [comment]
I see... I'll deploy again with https. Thanks
