### ISSUE TITLE
Alternative Currency documentation

### ISSUE THREAD

**Issue by fredhampton** [DemocracyEarth/sovereign#79]
Is there documentation for configuring for an a crypto currency that is not bitcoin ?

Thanks

**Comment by santisiri** [comment]
There is not, and I think it would be a fantastic idea to explore potential paths with Ethereum, Zero Cash, Litecoin (light mining for voting tokens makes sense to me).. and even the idea of a 'govchain' specifically for non-financial transactions.

Maybe this can be contributed to the /protocol repo we have and avoid making it just bitcoin-specific.

**Comment by fredhampton** [comment]
Thanks !!

**Comment by quardz** [comment]
I think its good to try with ethereum. As it maturing and becoming good dev platform. I'm reading the whitepaper and code. I will write more about it once i look potential alternative.
