### ISSUE TITLE
Handling of bad/unknown urls 

### ISSUE THREAD

**Issue by medied** [DemocracyEarth/sovereign#84]
What I currently see: 

![screen shot 2016-12-09 at 11 33 03 am](https://cloud.githubusercontent.com/assets/4752599/21062210/a074d5b0-be04-11e6-9f31-f20f0f742fb8.png)

![screen shot 2016-12-09 at 11 33 18 am](https://cloud.githubusercontent.com/assets/4752599/21062221/a75396e6-be04-11e6-9798-13799909f22e.png)

**Comment by santisiri** [comment]
i think we can implement a 404 template. there must be a ironrouter/meteor common practice for this?

**Comment by brylie** [comment]
We use FlowRouter in our main project at work. Here is an example of our [global 404 routing rule](https://github.com/apinf/platform/blob/develop/core/client/lib/router.js#L14-L19):


```js
// Define 404 route
FlowRouter.notFound = {
  action: function() {
    BlazeLayout.render('masterLayout', { main: 'notFound' });
  }
};
```

**Comment by brylie** [comment]
Prior to that, our IronRouter global configuration looked like this:

```js
Router.configure({
  layoutTemplate: 'masterLayout',
  loadingTemplate: 'loading',
  notFoundTemplate: 'notFound',
  ...
```

**Comment by medied** [comment]
Thanks @brylie, will start to work on this today
