### ISSUE TITLE
Remove third party CDN libraries and dependencies

### ISSUE THREAD

**Issue by brylie** [DemocracyEarth/sovereign#87]
There is growing concern about web surveillance, both by governments and the private sector. It is noted that including libraries from third parties, such as Google or Facebook, allows them to track people.

Please consider removing third party tracking software from Sovereign. Rather, include any necessary fonts, media, etc, in the project source. This way, Sovereign is truly sovereign.

# Examples
In `head.html` are the following snippets:

```html
<!-- Google -->
<script src="https://ajax.googleapis.com/ajax/libs/webfont/1.4.7/webfont.js"></script>
```

When clients load content from googleapis.com, Google is able to track them across the web.

There is also a link to Amazon CDN in the head.html:

```html
<meta property="og:image" content="https://s3-us-west-2.amazonaws.com/democracyearth/landing/earthflag.jpg">
```

Additionally, when starting a fresh instance of Soverign, there are server console warnings about several third party services:

- Amazon Web Services
- Mailgun
- Facebook
- Twitter
- Google Analytics

# Corporate nation-states
In effect, when we rely so heavily on centrally controlled, third-party services, we are simply reflecting the global corporate hegemony [we are trying so hard to disrupt](https://www.youtube.com/watch?v=yGmGWZCE4h0&t=592).

[![screenshot_20161216_123410](https://cloud.githubusercontent.com/assets/17307/21259889/385d4c18-c38c-11e6-86e8-af62179a08e6.png)](https://www.youtube.com/watch?v=yGmGWZCE4h0&t=592)

# References
- [How Online Tracking Companies Know Most of What You Do Online](https://www.eff.org/deeplinks/2009/09/online-trackers-and-social-networks)
- [The Future of Democracy | Santiago Siri](https://www.youtube.com/watch?v=yGmGWZCE4h0)

**Comment by santisiri** [comment]
Couldn't agree more with this. Great observation, will do.

**Comment by mairwilliams** [comment]
brilliant. i'm happy to see the matter discussed this early. thanks, man.

**Comment by brylie** [comment]
Also, when starting a fresh instance of Soverign, there are warnings about several third party services:

```
Verifying key configuration for this instance...
 MISSING SETTING: Amazon Web Services for resource storage keys not configured.
 FIX: Configure `AWSAccessKeyId`, `AWSSecretAccessKey` and `public.AWSHostingURL` on settings.json.
 MISSING SETTING: Mailgun SMTP server keys not configured.
 FIX: Configure `smtpServer` on settings.json.
 MISSING SETTING: Facebook API keys not configured.
 FIX: Configure `private.API.facebook.appId` and `private.API.facebook.appSecret` on settings.json.
 MISSING SETTING: Twitter API keys not configured.
 FIX: Configure `private.API.twitter.APIKey` and `private.API.twitter.APISecret` on settings.json.
 MISSING SETTING: Google Analytics tracking ID not configured.
 FIX: Configure `public.analyticsSettings["Google Analytics"].trackingId` on settings.json.
 MISSING SETTING: Kadira keys for performance app testing not configured.
 FIX: Configure `kadira.appId` and `kadira.appSecret` on settings.json.
```

While these services are useful, it would probably be beneficial to decouple Sovereign.

**Comment by brylie** [comment]
I opened issue #91 describing the development environment issue above.

**Comment by brylie** [comment]
It was verified in another issue that [Sovereign will not properly work without third party tracking software](https://github.com/DemocracyEarth/sovereign/issues/91#issuecomment-269332092).

**Comment by santisiri** [comment]
Excellent work.
