### ISSUE TITLE
Decentralization 

### ISSUE THREAD

**Issue by fredhampton** [DemocracyEarth/sovereign#88]
What are the plans to have Sovereign be decentralized ...without the need for centralized servers 

Thanks

**Comment by LucasIsasmendi** [comment]
We have some plans here https://github.com/DemocracyEarth/sovereign/projects
Mainly is migrate sovereign to desktop app to work similar to P2P network, sharing data with IPFS and 21.co to write the blockchain. We will start with hybrid approach, which means some files shared and others in a database

**Comment by fredhampton** [comment]
Thanks for your reply.
Are there IPFS and 21.co the final choices ?
Would there be an elegant way to shift to an alternative ?

**Comment by LucasIsasmendi** [comment]
IPFS and 21.co are not the final choice, they are part of an experiment.
If the experiment works, we will go a step further and try to adjust 21.co concepts to a vote system.
If not, we will try another option.
You can join our slack if you want to know more about it, or propose new experiments, we have #blockchain and #brainstorm channels to discuss these topics.
What do you mean with elegant way?
