### ISSUE TITLE
Cannot access ROOT url on fresh instance

### ISSUE THREAD

**Issue by brylie** [DemocracyEarth/sovereign#91]
I am getting browser console errors when starting a fresh instance of Soverign:

![screenshot_20161216_111647](https://cloud.githubusercontent.com/assets/17307/21257564/8798135e-c381-11e6-8b14-a4b76ceeac0f.png)

```js
Uncaught TypeError: Cannot read property 'analytics' of undefined (global-imports.js:18)
Uncaught ReferenceError: meteorInstall is not defined (app.js:1)
```

**Comment by brylie** [comment]
I would like to set up a local development environment, but cannot get past this error. I have followed the instructions in README.

**Comment by domi41** [comment]
I followed the `README` instructions as well, and _I cannot reproduce your issue_. I tried Mozilla Firefox `50.1.0`, Chrome `55.0.2883.87`, and even Chromium for good measure.

The only error I can find is when I'm logged out the console shows:
```
Exception in callback of async function: TypeError: Cannot read property 'username' of null
```

---

What's your output of `meteor npm version` ?

```
$ meteor npm version
{ npm: '3.10.9',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '56.1',
  modules: '46',
  node: '4.6.2',
  openssl: '1.0.2j',
  uv: '1.9.1',
  v8: '4.5.103.42',
  zlib: '1.2.8' }
```

```
$ meteor --version
Meteor 1.4.2.3
```

**Comment by brylie** [comment]
```
$ meteor npm version
{ npm: '3.10.9',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '56.1',
  modules: '46',
  node: '4.6.2',
  openssl: '1.0.2j',
  uv: '1.9.1',
  v8: '4.5.103.42',
  zlib: '1.2.8' }
```

```
$ meteor --version
Meteor 1.4.2.3 
```

**Comment by brylie** [comment]
Here is a screencast showing steps I take to reproduce:

[![screencast](https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Soverign-rootUrlBug.webm/1024px--Soverign-rootUrlBug.webm.jpg)](https://commons.wikimedia.org/wiki/File:Soverign-rootUrlBug.webm)

**Comment by domi41** [comment]
Perhaps try again after _disabling the script blocker_ ? (the red shield, top right)

**Comment by brylie** [comment]
Ah, that is interesting. It is also related to the [request to remove third party tracking software and dependencies from Sovereign](https://github.com/DemocracyEarth/sovereign/issues/87).

**Comment by brylie** [comment]
OK, it appears that uBlock Origin is blocking **analytics.js**:

![screenshot_20161228_103311](https://cloud.githubusercontent.com/assets/17307/21517621/1e9bb61e-cce9-11e6-8c76-3066b1cf128e.png)

How difficult would it be to remove the hard dependency on tracking software in Sovereign?
